import { exiftool } from '../exiftool'
import * as process from 'process'
import * as _fs from 'fs'
import * as _path from 'path'

const globule = require('globule')

function ellipsize(str: string, max: number) {
  if (str.length < max) {
    return str
  } else {
    return str.substring(0, max - 1) + '…'
  }
}

function log(obj: any) {
  console.log(ellipsize(JSON.stringify(obj), 200))
}

function usage() {
  console.log('Usage: `npm run tags IMG_DIR`')
  console.log('\nRebuilds src/metadata.ts from tags found in IMG_DIR.')
  process.exit(1)
}

const root = process.argv[2]
const files: string[] = globule.find(`${root}/**/*.jpg`)

if (files.length === 0) {
  console.error(`No files found in ${root}`)
  usage()
}

class Tag {
  values: any[] = []
  constructor(readonly tag: string) {
  } // tslint:disable-line

  get group(): string { return this.tag.split(':')[0] }
  get withoutGroup(): string { return this.tag.split(':')[1] }
  get valueType(): string {
    const n = this.withoutGroup
    if (n.includes('DateStamp')) {
      return 'ExifDate'
    } else if (n.includes('TimeStamp')) {
      return 'ExifTime'
    } else if (n.includes('Date')) {
      return 'ExifDateTime'
    } else {
      return typeof this.values[0]
    }
  }
}

class Tags {
  private m = new Map<string, Tag>()

  tag(tag: string) {
    const prevTag = this.m.get(tag)
    if (prevTag) {
      return prevTag
    } else {
      const t = new Tag(tag)
      this.m.set(tag, t)
      return t
    }
  }
  add(tag: string, value: any) {
    this.tag(tag).values.push(value)
  }
  tagsByPopularity(): Tag[] {
    const values = this.m.values()
    log({ values })
    return Array.from(values).sort((a, b) => a.values.length - b.values.length)
  }
}

function cmp(a: any, b: any): number {
  return a > b ? 1 : a < b ? -1 : 0
}

const tags = new Tags()

Promise.all(files.slice(0, 10).map(file => {
  return exiftool.readGrouped(file).then((metadata: any) => {
    Object.keys(metadata).forEach(key => {
      if (key.includes(':')) {
        tags.add(key, metadata[key])
      }
    }
    )
    process.stdout.write('.')
  }).catch(err => console.log(err))
})).then(() => {
  const destFile = _path.resolve(__dirname, '../../src/metadata.ts')
  const mdWriter = _fs.createWriteStream(destFile)
  mdWriter.write('// Autogenerated by `npm run tag`\n')
  mdWriter.write(`import { ExifDate, ExifTime, ExifDateTime } from './datetime'\n\n`)
  type GroupedTags = { [groupName: string]: Tag[] }
  const topK = tags.tagsByPopularity().slice(0, 25)
  const groupedTags: GroupedTags = {}
  topK.forEach(tag => {
    const key = tag.group;
    (groupedTags[key] || (groupedTags[key] = [])).push(tag)
  })
  const groupTagNames: string[] = []
  for (const group in groupedTags) {
    const groupTagName = `${group}Metadata`
    groupTagNames.push(groupTagName)
    mdWriter.write(`\nexport interface ${groupTagName} {`)
    const tags = groupedTags[group].sort((a, b) => cmp(a.tag, b.tag))
    tags.forEach(tag =>
      mdWriter.write(`  ${tag.withoutGroup}: ${tag.valueType} // ${ellipsize(JSON.stringify(tag.values[0]), 80)}`)
    )
    mdWriter.write(`}\n`)
  }
  mdWriter.write('\n')
  mdWriter.write('export interface Metadata\n')
  mdWriter.write(`  extends ${groupTagNames.join(', ')}`)
  mdWriter.write(' {\n')
  mdWriter.write('  SourceFile: string\n')
  mdWriter.write('  warnings: string[]\n')
  mdWriter.write('}\n')
  mdWriter.end()
  exiftool.end()
})


