/**
 * Please note that this is not an exhaustive tag list, but only the most commonly consumed tags.
 * PRs are welcome.
 */
export interface Metadata extends FileMetadata, ExifMetadata, MakerNotesMetadata, CompositeMetadata {
}

export interface FileMetadata {
  FileName: string
  Directory: string
  FileSize: string
  FileModifyDate: Date
  FileAccessDate: Date
  FileInodeChangeDate: Date
  FilePermissions: string
  FileType: string
  FileTypeExtension: string
  MIMEType: string
  ExifByteOrder: string
  ImageWidth: number
  ImageHeight: number
  EncodingProcess: string
  BitsPerSample: number
  ColorComponents: number
  YCbCrSubSampling: string
}

export interface ExifMetadata {
  ImageDescription: string
  Make: string
  Model: string
  Orientation: string
  XResolution: number
  YResolution: number
  ResolutionUnit: string
  Software: string
  ModifyDate: Date
  Artist: string
  YCbCrPositioning: string
  Copyright: string
  ExposureTime: number
  FNumber: number
  ExposureProgram: string
  ISO: number
  SensitivityType: string
  ExifVersion: string
  DateTimeOriginal: string
  CreateDate: Date
  ComponentsConfiguration: string
  ExposureCompensation: string
  MaxApertureValue: number
  MeteringMode: string
  LightSource: string
  Flash: string
  FocalLength: string
  UserComment: string
  FlashpixVersion: string
  ColorSpace: string
  ExifImageWidth: number
  ExifImageHeight: number
  InteropIndex: string
  InteropVersion: string
  FileSource: string
  CustomRendered: string
  ExposureMode: string
  WhiteBalance: string
  DigitalZoomRatio: number
  SceneCaptureType: string
  GainControl: string
  Contrast: string
  Saturation: string
  Sharpness: string
  LensInfo: string
  LensModel: string
  GPSVersionID: string
  Compression: string
  ThumbnailOffset: number
  ThumbnailLength: number
}

export interface MakerNotesMetadata {
  SpecialMode: string
  CameraID: string
  EquipmentVersion: string
  CameraType2: string
  SerialNumber: string
  InternalSerialNumber: string
  FocalPlaneDiagonal: string
  BodyFirmwareVersion: number
  LensType: string
  LensSerialNumber: string
  LensModel: string
  LensFirmwareVersion: number
  MaxApertureAtMinFocal: number
  MaxApertureAtMaxFocal: number
  MinFocalLength: number
  MaxFocalLength: number
  MaxAperture: number
  LensProperties: string
  Extender: string
  ExtenderSerialNumber: string
  ExtenderModel: string
  ExtenderFirmwareVersion: number
  ConversionLens: string
  FlashType: string
  FlashModel: string
  FlashFirmwareVersion: number
  FlashSerialNumber: string
  CameraSettingsVersion: string
  PreviewImageValid: string
  PreviewImageStart: number
  PreviewImageLength: number
  ExposureMode: string
  AELock: string
  MeteringMode: string
  ExposureShift: number
  MacroMode: string
  FocusMode: string
  FocusProcess: string
  AFSearch: string
  AFAreas: string
  AFPointSelected: string
  AFFineTune: string
  AFFineTuneAdj: string
  FlashMode: string
  FlashExposureComp: number
  FlashRemoteControl: string
  FlashControlMode: string
  FlashIntensity: string
  ManualFlashStrength: string
  WhiteBalance2: string
  WhiteBalanceTemperature: number
  WhiteBalanceBracket: string
  CustomSaturation: string
  ModifiedSaturation: string
  ContrastSetting: string
  SharpnessSetting: string
  ColorSpace: string
  SceneMode: string
  NoiseReduction: string
  DistortionCorrection: string
  ShadingCompensation: string
  CompressionFactor: number
  Gradation: string
  PictureMode: string
  PictureModeSaturation: string
  PictureModeContrast: string
  PictureModeSharpness: string
  PictureModeBWFilter: string
  PictureModeTone: string
  NoiseFilter: string
  ArtFilter: string
  PictureModeEffect: string
  ToneLevel: string
  ArtFilterEffect: string
  DriveMode: string
  PanoramaMode: string
  ImageStabilization: string
  StackedImage: string
  ManometerPressure: string
  ManometerReading: string
  ExtendedWBDetect: string
  DateTimeUTC: string
  RawDevVersion: string
  RawDevExposureBiasValue: number
  RawDevWhiteBalanceValue: number
  RawDevWBFineAdjustment: number
  RawDevGrayPoint: string
  RawDevSaturationEmphasis: string
  RawDevMemoryColorEmphasis: number
  RawDevContrastValue: string
  RawDevSharpnessValue: string
  RawDevColorSpace: string
  RawDevEngine: string
  RawDevNoiseReduction: string
  RawDevEditStatus: string
  RawDevSettings: string
  ImageProcessingVersion: string
  WB_RBLevels: string
  ColorMatrix: string
  BlackLevel2: string
  GainBase: number
  CropLeft: string
  CropTop: string
  CropWidth: number
  CropHeight: number
  SensorCalibration: string
  NoiseReduction2: string
  DistortionCorrection2: string
  ShadingCompensation2: string
  MultipleExposureMode: string
  AspectRatio: string
  AspectFrame: string
  FacesDetected: string
  FaceDetectArea: string
  MaxFaces: string
  FaceDetectFrameSize: string
  FaceDetectFrameCrop: string
  CameraTemperature: number
  FocusInfoVersion: string
  SceneDetect: number
  ZoomStepCount: number
  FocusStepCount: number
  FocusStepInfinity: number
  FocusStepNear: number
  FocusDistance: string
  AFPoint: string
  ExternalFlash: string
  ExternalFlashBounce: string
  ExternalFlashZoom: number
  InternalFlash: string
  ManualFlash: string
  MacroLED: string
  SensorTemperature: string
}

export interface CompositeMetadata {
  Aperture: number
  BlueBalance: number
  ExtenderStatus: string
  ImageSize: string
  LensID: string
  Megapixels: number
  PreviewImage: string
  RedBalance: number
  ScaleFactor35efl: number
  ShutterSpeed: number
  ThumbnailImage: string
  CircleOfConfusion: string
  DOF: string
  FOV: string
  FocalLength35efl: string
  HyperfocalDistance: string
  LightValue: number
}