// Autogenerated by `npm run tag`
/* tslint:disable:class-name */
import { ExifDate, ExifTime, ExifDateTime } from './datetime'

export interface CompositeMetadata {
  Aperture: number // 2.4
  BlueBalance: number // 1.557409
  CircleOfConfusion: string // "0.003 mm"
  ConditionalFEC: number // 0
  DOF: string // "inf (2.13 m - inf)"
  DriveMode: string // "Continuous Shooting"
  FOV: string // "57.2 deg"
  FlashType: string // "Built-In Flash"
  FocalLength35efl: string // "3.3 mm (35 mm equivalent: 33.0 mm)"
  GPSAltitude: string // "54 m Above Sea Level"
  GPSDateTime: ExifDateTime // "2015:09:05 16:27:22.9Z"
  GPSLatitude: number // "40.86041667 N"
  GPSLongitude: number // "25.83040556 E"
  GPSPosition: string // "40.86041667 N, 25.83040556 E"
  HyperfocalDistance: string // "1.51 m"
  ISO: number // 141
  ImageSize: string // "8x8"
  Lens: string // "6.1 - 61.0 mm"
  Lens35efl: string // "6.1 - 61.0 mm (35 mm equivalent: 39.8 - 398.4 mm)"
  LensID: string // "Unknown 6-61mm"
  LensSpec: string // "11-27.5mm f/3.5-5.6 [4]"
  LightValue: number // 13.4
  Megapixels: number // 0.000064
  PreviewImage: string // "(Binary data 347190 bytes, use -b option to extract)"
  RedBalance: number // 2.294406
  RedEyeReduction: string // "Off"
  ScaleFactor35efl: number // 10
  ShootingMode: string // "Program AE"
  ShutterCurtainHack: string // "1st-curtain sync"
  ShutterSpeed: string // "1/604"
  SubSecCreateDate: ExifDateTime // "2015:02:14 16:36:19.718"
  SubSecDateTimeOriginal: ExifDateTime // "2015:02:14 16:36:19.718"
  SubSecModifyDate: ExifDateTime // "2008:04:23 14:28:17.234"
  ThumbnailImage: string // "(Binary data 9462 bytes, use -b option to extract)"
  WB_RGGBLevels: string // "2338 1019 1019 1587"
}

export interface ExifToolMetadata {
  ExifToolVersion: number // 10.3
  Warning: string // "[minor] Unrecognized MakerNotes"
}

export interface FileMetadata {
  BitsPerSample: number // 8
  ColorComponents: number // 3
  Directory: string // "C:/Users/mrm/Desktop/test/Apple"
  EncodingProcess: string // "Baseline DCT, Huffman coding"
  ExifByteOrder: string // "Big-endian (Motorola, MM)"
  FileAccessDate: ExifDateTime // "2016:10:18 20:12:15-07:00"
  FileCreateDate: ExifDateTime // "2016:10:18 20:12:15-07:00"
  FileModifyDate: ExifDateTime // "2013:01:23 06:30:04-08:00"
  FileName: string // "Apple_iPad_mini.jpg"
  FilePermissions: string // "rw-rw-rw-"
  FileSize: string // "12 kB"
  FileType: string // "JPEG"
  FileTypeExtension: string // "jpg"
  ImageHeight: number // 8
  ImageWidth: number // 8
  MIMEType: string // "image/jpeg"
  PreviewImage: string // "(Binary data 133551 bytes, use -b option to extract)"
  YCbCrSubSampling: string // "YCbCr4:2:0 (2 2)"
}

export interface EXIFMetadata {
  ApertureValue: number // 2.4
  Artist: string // ""
  BrightnessValue: number // 8.717925387
  CFAPattern: string // "[Red,Green][Green,Blue]"
  ColorSpace: string // "sRGB"
  ComponentsConfiguration: string // "Y, Cb, Cr, -"
  CompressedBitsPerPixel: number // 2
  Compression: string // "JPEG (old-style)"
  Contrast: string // "Normal"
  Copyright: string // ""
  CreateDate: ExifDateTime // "2012:11:10 10:46:58"
  CustomRendered: string // "Unknown (2)"
  DateTimeOriginal: ExifDateTime // "2012:11:10 10:46:58"
  DigitalZoomRatio: number // 1.042758621
  ExifImageHeight: number // 1936
  ExifImageWidth: number // 2592
  ExifVersion: string // "0221"
  ExposureCompensation: number // 0
  ExposureIndex: number // 200
  ExposureMode: string // "Auto"
  ExposureProgram: string // "Program AE"
  ExposureTime: string // "1/604"
  FNumber: number // 2.4
  FileSource: string // "Reflection Print Scanner"
  Flash: string // "No flash function"
  FlashpixVersion: string // "0100"
  FocalLength: string // "3.3 mm"
  FocalLengthIn35mmFormat: string // "33 mm"
  FocalPlaneResolutionUnit: string // "inches"
  FocalPlaneXResolution: number // 12401.91388
  FocalPlaneYResolution: number // 12461.53846
  GPSAltitude: string // "54 m"
  GPSAltitudeRef: string // "Above Sea Level"
  GPSDateStamp: ExifDate // "2015:09:05"
  GPSLatitude: number // 40.86041667
  GPSLatitudeRef: string // "North"
  GPSLongitude: number // 25.83040556
  GPSLongitudeRef: string // "East"
  GPSTimeStamp: ExifTime // "16:27:22.9"
  GPSVersionID: string // "2.2.0.0"
  GainControl: string // "Unknown (256)"
  ISO: number // 32
  ImageDescription: string // "Back Camera"
  ImageHeight: number // 60
  ImageWidth: number // 80
  InteropIndex: string // "R98 - DCF basic file (sRGB)"
  InteropVersion: string // "0100"
  LensInfo: string // "3.3mm f/2.4"
  LensModel: string // "iPad mini 2 back camera 3.3mm f/2.4"
  LightSource: string // "Daylight"
  Make: string // "Apple"
  MaxApertureValue: number // 2.8
  MeteringMode: string // "Spot"
  Model: string // "iPad mini"
  ModifyDate: ExifDateTime // "2012:11:10 10:46:58"
  Orientation: string // "Horizontal (normal)"
  OwnerName: string // ""
  RecommendedExposureIndex: number // 1600
  RelatedImageHeight: number // 1944
  RelatedImageWidth: number // 2592
  RelatedSoundFile: string // "            "
  ResolutionUnit: string // "inches"
  Saturation: string // "Normal"
  SceneCaptureType: string // "Standard"
  SceneType: string // "Directly photographed"
  SensingMethod: string // "One-chip color area"
  SensitivityType: string // "Recommended Exposure Index"
  Sharpness: string // "Normal"
  ShutterSpeedValue: string // "1/604"
  Software: string // "6.0.1"
  SubSecTime: number // 234
  SubSecTimeDigitized: number // 718
  SubSecTimeOriginal: number // 718
  SubjectDistance: string // "0.488 m"
  SubjectDistanceRange: string // "Unknown"
  ThumbnailLength: number // 9462
  ThumbnailOffset: number // 688
  UserComment: string // ""
  WhiteBalance: string // "Auto"
  XResolution: number // 72
  YCbCrPositioning: string // "Centered"
  YResolution: number // 72
}

export interface MakerNotesMetadata {
  AEBBracketValue: string // "+0.25"
  AELock: string // "Off"
  AESetting: string // "Normal AE"
  AFAreaHeight: number // 42
  AFAreaHeights: string // "37 37 37 37 37 37 37 37 37"
  AFAreaMode: string // "Auto"
  AFAreaWidth: number // 369
  AFAreaWidths: string // "53 53 53 53 53 53 53 53 53"
  AFAreaXPositions: string // "-54 0 53 -54 0 53 -54 0 53"
  AFAreaYPositions: string // "-38 -38 -38 0 0 0 38 38 38"
  AFAreas: string // "none"
  AFAssistBeam: string // "Emits"
  AFFineTune: string // "Off"
  AFFineTuneAdj: number // 0
  AFImageHeight: number // 240
  AFImageWidth: number // 320
  AFPoint: string // "Auto AF point selection"
  AFPointSelected: string // "n/a"
  AFPointsInFocus: number // 4
  AFPointsSelected: string // "0,1,2,3,4,5,6"
  AFSearch: string // "Not Ready"
  AspectFrame: string // "0 0 3967 2975"
  AspectRatio: string // "3:2"
  AutoDistortionControl: string // "Off"
  AutoExposureBracketing: string // "On"
  AutoISO: number // 100
  AutoLightingOptimizer: string // "Enable"
  AutoRotate: string // "None"
  AuxiliaryLens: string // "Off"
  AverageBlackLevel: string // "1024 1024 1024 1024"
  BWMode: string // "Off"
  BaseISO: number // 50
  BlackLevel2: string // "63 63 63 63"
  BlackMaskBottomBorder: number // 0
  BlackMaskLeftBorder: number // 0
  BlackMaskRightBorder: number // 0
  BlackMaskTopBorder: number // 0
  BodyFirmwareVersion: number // 73
  BracketMode: string // "Off"
  BracketShotNumber: number // 0
  BracketValue: number // 0
  Brightness: string // "Normal"
  BulbDuration: number // 0
  CameraID: string // "OLYMPUS DIGITAL CAMERA"
  CameraISO: string // "Auto"
  CameraSettingsVersion: string // "0100"
  CameraTemperature: string // "27 C"
  CameraType: string // "DV Camera"
  CameraType2: string // "u7040,S7040"
  CanonExposureMode: string // "Program AE"
  CanonFirmwareVersion: string // "Firmware Version 2.01"
  CanonFlashMode: string // "Auto"
  CanonImageHeight: number // 1840
  CanonImageSize: string // "Large"
  CanonImageType: string // "IMG:iVIS DC50 JPEG"
  CanonImageWidth: number // 3264
  CanonModelID: string // "DC50"
  Categories: string // "(none)"
  ColorDataVersion: string // "5 (450D/1000D)"
  ColorMatrix: string // "366 -92 -18 -52 412 -104 -6 -108 370"
  ColorMode: string // "Color"
  ColorSpace: string // "sRGB"
  ColorTempAsShot: number // 4551
  ColorTempAuto: number // 4551
  ColorTempCloudy: number // 6000
  ColorTempDaylight: number // 5200
  ColorTempFlash: number // 6456
  ColorTempFluorescent: number // 3901
  ColorTempKelvin: number // 5190
  ColorTempMeasured: number // 4276
  ColorTempShade: number // 7000
  ColorTempTungsten: number // 3200
  ColorTemperature: number // 5200
  ColorTone: string // "Normal"
  Compression: string // "JPEG (old-style)"
  CompressionFactor: number // 4
  ContinuousDrive: string // "Continuous"
  Contrast: string // "Normal"
  ContrastSetting: string // "0 (min -2, max 2)"
  ControlMode: string // "n/a"
  CropBottomMargin: number // 0
  CropHiSpeed: string // "Off (4620x3084 cropped to 4620x3084 at pixel 0,0)"
  CropLeftMargin: number // 0
  CropRightMargin: number // 0
  CropTopMargin: number // 0
  CroppedImageHeight: number // 3456
  CroppedImageLeft: number // 0
  CroppedImageTop: number // 0
  CroppedImageWidth: number // 5184
  CustomPictureStyleFileName: string // ""
  CustomSaturation: string // "0 (min -2, max 2)"
  DataDump: string // "(Binary data 494 bytes, use -b option to extract)"
  DateStampMode: string // "Off"
  DaylightSavings: string // "Off"
  DeviceType: string // "Compact Digital Camera"
  DigitalGain: number // 0
  DigitalZoom: string // "None"
  DisplayAperture: number // 3.9
  DistortionCorrection: string // "Off"
  DistortionCorrection2: string // "On"
  DriveMode: string // "Single Shot"
  DustRemovalData: string // "(Binary data 1024 bytes, use -b option to extract)"
  EasyMode: string // "Manual"
  EquipmentVersion: string // "0100"
  ExposureBracketValue: number // 0
  ExposureCompensation: number // 0
  ExposureDifference: number // 0
  ExposureLevelIncrements: string // "1/3 Stop"
  ExposureMode: string // "Program"
  ExposureShift: string // "undef"
  ExposureTime: string // "1/64"
  ExtendedWBDetect: string // "Off"
  ExternalFlash: string // "Off"
  ExternalFlashBounce: string // "Bounce or Off"
  ExternalFlashExposureComp: number // 0
  ExternalFlashFirmware: string // "n/a"
  ExternalFlashFlags: string // "(none)"
  ExternalFlashZoom: number // 0
  FNumber: number // 2.9
  FaceDetect: string // "Off"
  FaceDetectArea: string // "(Binary data 383 bytes, use -b option to extract)"
  FaceDetectFrameSize: string // "320 240"
  FaceRecognition: string // "Off"
  FacesDetected: number // 0
  FileNumber: string // "196-9624"
  FilterEffect: string // "None"
  FirmwareRevision: string // "1.00 rev 3.00"
  FirmwareVersion: string // "1.0.3"
  FlashActivity: number // 0
  FlashBits: string // "E-TTL, Built-in"
  FlashCommanderMode: string // "Off"
  FlashControlMode: string // "Off"
  FlashExposureComp: number // 0
  FlashExposureLock: string // "Off"
  FlashGNDistance: number // 0
  FlashGroupAControlMode: string // "Off"
  FlashGroupBCompensation: number // 0
  FlashGroupBControlMode: string // "Off"
  FlashGuideNumber: number // 8.46875
  FlashInfoVersion: string // "0200"
  FlashIntensity: string // "n/a"
  FlashMode: string // "Did Not Fire"
  FlashOutput: number // 175
  FlashRemoteControl: string // "Off"
  FlashSetting: string // "Normal"
  FlashSyncSpeedAv: string // "Auto"
  FlashType: string // ""
  FocalLength: string // "15.53 mm"
  FocalPlaneDiagonal: string // "7.665 mm"
  FocalPlaneXSize: string // "5.44 mm"
  FocalPlaneYSize: string // "4.06 mm"
  FocalType: string // "Zoom"
  FocalUnits: string // "100/mm"
  FocusContinuous: string // "Continuous"
  FocusDistance: string // "3.98 m"
  FocusDistanceLower: string // "0 m"
  FocusDistanceUpper: string // "65.53 m"
  FocusInfoVersion: string // "0100"
  FocusMode: string // "Single"
  FocusProcess: string // "AF Not Used"
  FocusRange: string // "Auto"
  FocusStepCount: number // 646
  FocusStepInfinity: number // 642
  FocusStepNear: number // 692
  Gradation: string // "n/a; User-Selected"
  HDR: string // "Off"
  HDRInfoVersion: string // "0200"
  HDRLevel: string // "Auto"
  HDRLevel2: string // "Auto"
  HDRSmoothing: string // "Off"
  HighISONoiseReduction: string // "Off"
  HighlightTonePriority: string // "Disable"
  HueAdjustment: string // "None"
  ISO: number // 100
  ISO2: number // 159
  ISOExpansion: string // "On"
  ISOExpansion2: string // "Off"
  ISOSelection: string // "Auto"
  ImageAdjustment: string // "Auto"
  ImageBoundary: string // "0 0 4608 3072"
  ImageDataSize: number // 5500790
  ImageProcessing: string // ""
  ImageProcessingVersion: string // "0112"
  ImageStabilization: string // "On"
  ImageUniqueID: string // "25c584939cdf2fe47ac7af920c3ef487"
  IntelligentContrast: string // "Off"
  InternalFlash: string // "TTL"
  InternalSerialNumber: string // "K0027622"
  Lens: string // "11-27.5mm f/3.5-5.6"
  LensDataVersion: string // "0403"
  LensDistortionParams: string // "-30641 21134 32382 25674 17516 32364"
  LensFStops: number // 7.67
  LensModel: string // "EF-S18-55mm f/3.5-5.6 IS"
  LensSerialNumber: string // "00002042bc"
  LensType: string // "n/a"
  LinearityUpperMargin: number // 10000
  LiveViewShooting: string // "Off"
  LongExposureNoiseReduction: string // "Off"
  LongExposureNoiseReduction2: string // "Off"
  Macro: string // "Off"
  MacroLED: string // "Off"
  MacroMode: string // "Unknown (0)"
  MagicFilter: string // "Off; 1280; 0; 0"
  MakerNoteVersion: number // 2.11
  ManometerPressure: string // "0 kPa"
  ManometerReading: string // "0 m, 0 ft"
  ManualFlash: string // "Off"
  ManualFlashOutput: string // "n/a"
  ManualFlashStrength: string // "n/a"
  ManualFocusDistance: string // "undef"
  MaxAperture: number // 2.9
  MaxApertureAtMaxFocal: number // 5.7
  MaxApertureAtMinFocal: number // 4.5
  MaxFaces: string // "16 16 16"
  MaxFocalLength: string // "61 mm"
  MeasuredEV: number // 5
  MeasuredEV2: number // 12.625
  MeasuredRGGB: string // "471 1024 1024 581"
  MeteringMode: string // "Evaluative"
  MinAperture: number // 6.9
  MinFocalLength: string // "6.1 mm"
  MirrorLockup: string // "Disable"
  ModifiedSaturation: string // "Off"
  MultiExposureAutoGain: string // "Off"
  MultiExposureMode: string // "Off"
  MultiExposureShots: number // 0
  MultiExposureVersion: string // "0100"
  MyColorMode: string // "Off"
  NDFilter: string // "n/a"
  NoiseFilter: string // "n/a"
  NoiseReduction: string // "Off"
  NoiseReduction2: string // "(none)"
  NumAFPoints: number // 9
  OneTouchWB: string // "Off"
  OpticalZoomCode: string // "n/a"
  OwnerName: string // ""
  PanoramaMode: string // "Off"
  PerChannelBlackLevel: string // "1023 1024 1023 1024"
  PeripheralIlluminationCorr: string // "On"
  PeripheralLightingSetting: string // "Off"
  PhotoEffect: string // "Off"
  PictureControlAdjust: string // "Default Settings"
  PictureControlBase: string // "Standard"
  PictureControlName: string // "Standard"
  PictureControlQuickAdjust: string // "Normal"
  PictureControlVersion: string // "0100"
  PictureMode: string // "i-Enhance; 2"
  PictureStyle: string // "None"
  PictureStylePC: string // "None; None; None"
  PictureStyleUserDef: string // "Standard; Standard; Standard"
  PreCaptureFrames: number // 0
  PreviewImageLength: number // 347190
  PreviewImageStart: number // 1296968
  PreviewImageValid: string // "Yes"
  PrimaryAFPoint: number // 4
  ProgramShift: number // 0
  Quality: string // "Superfine"
  RawDataByteOrder: string // "Little-endian (Intel, II)"
  RawDataCFAPattern: string // "Swap"
  RawDevEditStatus: string // "Original"
  RawDevVersion: string // "0100"
  RawJpgSize: string // "Large"
  RawMeasuredRGGB: string // "40661 82449 82146 41069"
  RecordMode: string // "JPEG"
  Resolution: number // 2
  ResolutionUnit: string // "inches"
  RetouchHistory: string // "None"
  Rotation: number // 0
  SamsungModelID: string // "Various Models (0x3000000)"
  Saturation: string // "Normal"
  SceneAssist: string // ""
  SceneDetect: number // 2
  SceneMode: string // ""
  SelfTimer: string // "Off"
  SelfTimer2: number // 0.1
  SensorBlueLevel: number // 0
  SensorBottomBorder: number // 2322
  SensorCalibration: string // "0 0"
  SensorHeight: number // 2328
  SensorLeftBorder: number // 52
  SensorRedLevel: number // 0
  SensorRightBorder: number // 3507
  SensorTopBorder: number // 19
  SensorWidth: number // 3516
  SequenceNumber: number // 0
  SerialNumber: string // "0320131248"
  SetButtonWhenShooting: string // "Default (no function)"
  ShadingCompensation: string // "Off"
  ShadingCompensation2: string // "On"
  Sharpness: string // 0
  SharpnessFrequency: string // "n/a"
  SharpnessSetting: string // "0 (min -2, max 2)"
  ShootingMode: string // "Delay"
  ShotInfoVersion: string // "0400"
  ShutterCount: number // 266
  SlowShutter: string // "n/a"
  SpecialMode: string // "Normal, Sequence: 0, Panorama: (none)"
  SpecularWhiteLevel: number // 15120
  SpotMeteringMode: string // "Center"
  TargetAperture: number // 2.8
  TargetExposureTime: string // "1/60"
  ThumbnailImageValidArea: string // "0 0 0 0"
  TimeZone: string // "+00:00"
  TimeZoneCity: string // "London"
  ToneCurve: string // "Standard"
  ToningEffect: string // "None"
  ToningSaturation: string // "n/a"
  VRDOffset: number // 0
  VRInfoVersion: string // "0101"
  VRMode: string // "Normal"
  ValidAFPoints: number // 9
  VibrationReduction: string // "Off"
  VignettingCorrVersion: number // 0
  WBBracketMode: string // "Off"
  WBBracketValueAB: number // 0
  WBBracketValueGM: number // 0
  WBShiftAB: number // 0
  WBShiftGM: number // 0
  WB_RBLevels: string // "1.59375 2.1640625 1 1"
  WB_RGGBLevelsAsShot: string // "2338 1019 1019 1587"
  WB_RGGBLevelsAuto: string // "2338 1023 1023 1587"
  WB_RGGBLevelsCloudy: string // "2639 1023 1023 1353"
  WB_RGGBLevelsDaylight: string // "2425 1023 1023 1492"
  WB_RGGBLevelsFlash: string // "2735 1023 1023 1306"
  WB_RGGBLevelsFluorescent: string // "2038 1023 1023 1969"
  WB_RGGBLevelsKelvin: string // "2185 1024 1024 1535"
  WB_RGGBLevelsMeasured: string // "1912 1028 1019 1791"
  WB_RGGBLevelsShade: string // "2847 1023 1023 1249"
  WB_RGGBLevelsTungsten: string // "1597 1023 1023 2302"
  WhiteBalance: string // "Auto"
  WhiteBalance2: string // "Auto"
  WhiteBalanceBias: number // 0
  WhiteBalanceBlue: number // 0
  WhiteBalanceBracket: number // 0
  WhiteBalanceFineTune: string // "0 0"
  WhiteBalanceRed: number // 0
  WhiteBalanceTemperature: number // 5300
  WhiteBoard: number // 0
  XResolution: number // 300
  YCbCrPositioning: string // "Co-sited"
  YResolution: number // 300
  ZoomSourceWidth: number // 2584
  ZoomStepCount: number // 1
  ZoomTargetWidth: number // 2584
}

export interface JFIFMetadata {
  JFIFVersion: number // 1.01
  ResolutionUnit: string // "inches"
  XResolution: number // 72
  YResolution: number // 72
}

export interface PrintIMMetadata {
  PrintIMVersion: string // "0300"
}

export interface XMPMetadata {
  CreatorTool: string // "Photos 1.0.1"
  Rating: number // 2
  XMPToolkit: string // "XMP Core 5.4.0"
}

export interface MPFMetadata {
  DependentImage1EntryNumber: number // 0
  DependentImage2EntryNumber: number // 0
  ImageUIDList: string // "(Binary data 66 bytes, use -b option to extract)"
  MPFVersion: string // "0100"
  MPImageFlags: string // "Dependent child image"
  MPImageFormat: string // "JPEG"
  MPImageLength: number // 681513
  MPImageStart: number // 7732736
  MPImageType: string // "Large Thumbnail (full HD equivalent)"
  NumberOfImages: number // 2
  TotalFrames: number // 1
}

export interface Tags extends
  CompositeMetadata,
  ExifToolMetadata,
  FileMetadata,
  EXIFMetadata,
  MakerNotesMetadata,
  JFIFMetadata,
  PrintIMMetadata,
  XMPMetadata,
  MPFMetadata {
  SourceFile: string
  warnings: string[]
}

export interface GroupedMetadata {
  SourceFile: string
  warnings: string[]
  Composite: CompositeMetadata
  ExifTool: ExifToolMetadata
  File: FileMetadata
  EXIF: EXIFMetadata
  MakerNotes: MakerNotesMetadata
  JFIF: JFIFMetadata
  PrintIM: PrintIMMetadata
  XMP: XMPMetadata
  MPF: MPFMetadata
}
