/* tslint:disable:class-name */
import { ExifDate, ExifTime, ExifDateTime } from './datetime'

// Autogenerated by "npm run mktags" on Sun Oct 23 2016.

// Comments by each tag include popularity (★★★ is > 70% of cameras, ☆☆☆ is rare),
// followed by a checkmark if the tag is used by recent, popular devices (like iPhones)
// An example value, JSON stringified, follows the popularity ratings.

export interface ExifToolTags {
  /** ★★★ ✔ 10.31 */
  ExifToolVersion: number
  /** ☆☆☆   "Bad MakerNotes offset for tag 0x0000" */
  Warning: string
}

export interface FileTags {
  /** ★★★ ✔ [8] */
  BitsPerSample: number[]
  /** ★★★ ✔ 3 */
  ColorComponents: number
  /** ☆☆☆   "AppleMark\n" */
  Comment: string
  /** ☆☆☆ ✔ "d41d8cd98f00b204e9800998ecf8427e" */
  CurrentIPTCDigest: string
  /** ★★★ ✔ "C:/Users/mrm/src/exif/test-images/Apple" */
  Directory: string
  /** ★★★ ✔ "Baseline DCT, Huffman coding" */
  EncodingProcess: string
  /** ★★★ ✔ "Big-endian (Motorola, MM)" */
  ExifByteOrder: string
  /** ★★★ ✔ {"year":2016,"month":10,"day":18,"hour":20,"minute":12,"second":15,"tzoffsetMin… */
  FileAccessDate: ExifDateTime
  /** ★★★ ✔ {"year":2016,"month":10,"day":18,"hour":20,"minute":12,"second":15,"tzoffsetMin… */
  FileCreateDate: ExifDateTime
  /** ★★★ ✔ {"year":2013,"month":1,"day":23,"hour":6,"minute":30,"second":4,"tzoffsetMinute… */
  FileModifyDate: ExifDateTime
  /** ★★★ ✔ "Apple_iPad_mini.jpg" */
  FileName: string
  /** ★★★ ✔ "rw-rw-rw-" */
  FilePermissions: string
  /** ★★★ ✔ "12 kB" */
  FileSize: string
  /** ★★★ ✔ "JPEG" */
  FileType: string
  /** ★★★ ✔ "jpg" */
  FileTypeExtension: string
  /** ★★★ ✔ 8 */
  ImageHeight: number
  /** ★★★ ✔ 8 */
  ImageWidth: number
  /** ★★★ ✔ "image/jpeg" */
  MIMEType: string
  /** ☆☆☆ ✔ "(Binary data 83787 bytes, use -b option to extract)" */
  PreviewImage: string
  /** ★★★ ✔ "YCbCr4:2:0 (2 2)" */
  YCbCrSubSampling: string
}

export interface EXIFTags {
  /** ★☆☆ ✔ 2.4 */
  ApertureValue: number
  /** ☆☆☆ ✔ "" */
  Artist: string
  /** ☆☆☆   [8,8,8] */
  BitsPerSample: number[]
  /** ☆☆☆ ✔ 8.717925387 */
  BrightnessValue: number
  /** ☆☆☆ ✔ "[Blue,Green][Green,Red]" */
  CFAPattern: string
  /** ★★★ ✔ "sRGB" */
  ColorSpace: string
  /** ★★★ ✔ "Y, Cb, Cr, -" */
  ComponentsConfiguration: string
  /** ★★☆ ✔ 2 */
  CompressedBitsPerPixel: number
  /** ★★★ ✔ "JPEG (old-style)" */
  Compression: string
  /** ★☆☆ ✔ "Normal" */
  Contrast: string
  /** ☆☆☆ ✔ "" */
  Copyright: string
  /** ★★★ ✔ {"year":2012,"month":11,"day":10,"hour":10,"minute":46,"second":58} */
  CreateDate: ExifDateTime
  /** ★★☆ ✔ "Unknown (2)" */
  CustomRendered: string
  /** ★★★ ✔ {"year":2012,"month":11,"day":10,"hour":10,"minute":46,"second":58} */
  DateTimeOriginal: ExifDateTime
  /** ☆☆☆ ✔ "(Binary data 4 bytes, use -b option to extract)" */
  DeviceSettingDescription: string
  /** ★★☆ ✔ 1.042758621 */
  DigitalZoomRatio: number
  /** ★★★ ✔ 1936 */
  ExifImageHeight: number
  /** ★★★ ✔ 2592 */
  ExifImageWidth: number
  /** ★★★ ✔ "0221" */
  ExifVersion: string
  /** ★★★ ✔ 0 */
  ExposureCompensation: number
  /** ☆☆☆ ✔ 200 */
  ExposureIndex: number
  /** ★★★ ✔ "Auto" */
  ExposureMode: string
  /** ★★☆ ✔ "Program AE" */
  ExposureProgram: string
  /** ★★★ ✔ "1/604" */
  ExposureTime: string
  /** ★★★ ✔ 2.4 */
  FNumber: number
  /** ★★☆ ✔ "Reflection Print Scanner" */
  FileSource: string
  /** ★★★ ✔ "No flash function" */
  Flash: string
  /** ★★★ ✔ "0100" */
  FlashpixVersion: string
  /** ★★★ ✔ "3.3 mm" */
  FocalLength: string
  /** ★☆☆ ✔ "33 mm" */
  FocalLengthIn35mmFormat: string
  /** ★☆☆ ✔ "inches" */
  FocalPlaneResolutionUnit: string
  /** ★☆☆ ✔ 12401.91388 */
  FocalPlaneXResolution: number
  /** ★☆☆ ✔ 12461.53846 */
  FocalPlaneYResolution: number
  /** ☆☆☆ ✔ "54 m" */
  GPSAltitude: string
  /** ☆☆☆ ✔ "Above Sea Level" */
  GPSAltitudeRef: string
  /** ☆☆☆ ✔ {"year":2015,"month":9,"day":5,"tzoffsetMinutes":0} */
  GPSDateStamp: ExifDate
  /** ☆☆☆ ✔ 274.8004158 */
  GPSDestBearing: number
  /** ☆☆☆ ✔ "True North" */
  GPSDestBearingRef: string
  /** ☆☆☆ ✔ "25 m" */
  GPSHPositioningError: string
  /** ☆☆☆ ✔ 94.8004158 */
  GPSImgDirection: number
  /** ☆☆☆ ✔ "True North" */
  GPSImgDirectionRef: string
  /** ☆☆☆ ✔ 40.86041667 */
  GPSLatitude: number
  /** ☆☆☆ ✔ "North" */
  GPSLatitudeRef: string
  /** ☆☆☆ ✔ 25.83040556 */
  GPSLongitude: number
  /** ☆☆☆ ✔ "East" */
  GPSLongitudeRef: string
  /** ☆☆☆   "WGS-84" */
  GPSMapDatum: string
  /** ☆☆☆   "GPS" */
  GPSProcessingMethod: string
  /** ☆☆☆   5 */
  GPSSatellites: number
  /** ☆☆☆ ✔ 0 */
  GPSSpeed: number
  /** ☆☆☆ ✔ "km/h" */
  GPSSpeedRef: string
  /** ☆☆☆   "Measurement Active" */
  GPSStatus: string
  /** ☆☆☆ ✔ "16:27:22.9" */
  GPSTimeStamp: string
  /** ☆☆☆ ✔ "2.2.0.0" */
  GPSVersionID: string
  /** ☆☆☆ ✔ "None" */
  GainControl: string
  /** ☆☆☆   2.2 */
  Gamma: number
  /** ☆☆☆ ✔ "iPhone (iPhone OS 8.1.2)" */
  HostComputer: string
  /** ★★☆ ✔ 32 */
  ISO: number
  /** ★☆☆ ✔ "Back Camera" */
  ImageDescription: string
  /** ☆☆☆ ✔ 60 */
  ImageHeight: number
  /** ☆☆☆ ✔ "b6cbe2dd40d4d9de189b18448524a417" */
  ImageUniqueID: string
  /** ☆☆☆ ✔ 80 */
  ImageWidth: number
  /** ★★★ ✔ "R98 - DCF basic file (sRGB)" */
  InteropIndex: string
  /** ★★★ ✔ "0100" */
  InteropVersion: string
  /** ☆☆☆ ✔ "3.3mm f/2.4" */
  LensInfo: string
  /** ☆☆☆ ✔ "Apple" */
  LensMake: string
  /** ☆☆☆ ✔ "iPad mini 2 back camera 3.3mm f/2.4" */
  LensModel: string
  /** ☆☆☆ ✔ "00002042bc" */
  LensSerialNumber: string
  /** ★☆☆ ✔ "Daylight" */
  LightSource: string
  /** ★★★ ✔ "Apple" */
  Make: string
  /** ★★☆ ✔ 2.8 */
  MaxApertureValue: number
  /** ★★★ ✔ "Spot" */
  MeteringMode: string
  /** ★★★ ✔ "iPad mini" */
  Model: string
  /** ★★★ ✔ {"year":2012,"month":11,"day":10,"hour":10,"minute":46,"second":58} */
  ModifyDate: ExifDateTime
  /** ☆☆☆ ✔ -230 */
  OffsetSchema: number
  /** ★★★ ✔ "Horizontal (normal)" */
  Orientation: string
  /** ☆☆☆ ✔ "" */
  OwnerName: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  Padding: string
  /** ☆☆☆   "YCbCr" */
  PhotometricInterpretation: string
  /** ☆☆☆   "Chunky" */
  PlanarConfiguration: string
  /** ☆☆☆   "0.64 0.33 0.3 0.6 0.15 0.06" */
  PrimaryChromaticities: string
  /** ☆☆☆   0 */
  Rating: number
  /** ☆☆☆ ✔ 1600 */
  RecommendedExposureIndex: number
  /** ☆☆☆   "0 255 128 255 128 255" */
  ReferenceBlackWhite: string
  /** ☆☆☆   1944 */
  RelatedImageHeight: number
  /** ☆☆☆   2592 */
  RelatedImageWidth: number
  /** ☆☆☆   "RelatedSound" */
  RelatedSoundFile: string
  /** ★★★ ✔ "inches" */
  ResolutionUnit: string
  /** ☆☆☆   60 */
  RowsPerStrip: number
  /** ☆☆☆   3 */
  SamplesPerPixel: number
  /** ★☆☆ ✔ "Normal" */
  Saturation: string
  /** ★★☆ ✔ "Standard" */
  SceneCaptureType: string
  /** ★☆☆ ✔ "Directly photographed" */
  SceneType: string
  /** ★☆☆ ✔ "One-chip color area" */
  SensingMethod: string
  /** ☆☆☆ ✔ "Recommended Exposure Index" */
  SensitivityType: string
  /** ☆☆☆ ✔ "000019900153" */
  SerialNumber: string
  /** ★☆☆ ✔ "Normal" */
  Sharpness: string
  /** ★☆☆ ✔ "1/604" */
  ShutterSpeedValue: string
  /** ★★☆ ✔ "6.0.1" */
  Software: string
  /** ☆☆☆   9600 */
  StripByteCounts: number
  /** ☆☆☆   796 */
  StripOffsets: number
  /** ☆☆☆ ✔ 234 */
  SubSecTime: number
  /** ☆☆☆ ✔ 718 */
  SubSecTimeDigitized: number
  /** ☆☆☆ ✔ 718 */
  SubSecTimeOriginal: number
  /** ☆☆☆ ✔ "1836 859 484 484" */
  SubjectArea: string
  /** ☆☆☆ ✔ "0.488 m" */
  SubjectDistance: string
  /** ★☆☆ ✔ "Unknown" */
  SubjectDistanceRange: string
  /** ★★★ ✔ 9462 */
  ThumbnailLength: number
  /** ★★★ ✔ 688 */
  ThumbnailOffset: number
  /** ★☆☆ ✔ "" */
  UserComment: string
  /** ★★★ ✔ "Auto" */
  WhiteBalance: string
  /** ☆☆☆   "0.3127 0.329" */
  WhitePoint: string
  /** ☆☆☆ ✔ "" */
  XPAuthor: string
  /** ☆☆☆   "" */
  XPKeywords: string
  /** ★★★ ✔ 72 */
  XResolution: number
  /** ☆☆☆   "0.299 0.587 0.114" */
  YCbCrCoefficients: string
  /** ★★★ ✔ "Centered" */
  YCbCrPositioning: string
  /** ☆☆☆   "YCbCr4:2:2 (2 1)" */
  YCbCrSubSampling: string
  /** ★★★ ✔ 72 */
  YResolution: number
}

export interface CompositeTags {
  /** ★★★ ✔ 2.4 */
  Aperture: number
  /** ☆☆☆ ✔ "Off" */
  AutoFocus: string
  /** ☆☆☆ ✔ 1.557409 */
  BlueBalance: number
  /** ★★☆ ✔ "0.003 mm" */
  CircleOfConfusion: string
  /** ☆☆☆   0 */
  ConditionalFEC: number
  /** ☆☆☆ ✔ "inf (2.13 m - inf)" */
  DOF: string
  /** ☆☆☆   {"year":2005,"month":11,"day":19} */
  DateCreated: ExifDate
  /** ☆☆☆ ✔ {"year":2014,"month":10,"day":31,"hour":13,"minute":15,"second":35} */
  DateTimeCreated: ExifDateTime
  /** ☆☆☆ ✔ {"year":2016,"month":8,"day":12,"hour":13,"minute":28,"second":50} */
  DigitalCreationDateTime: ExifDateTime
  /** ☆☆☆ ✔ "Continuous Shooting" */
  DriveMode: string
  /** ☆☆☆ ✔ "Not attached" */
  ExtenderStatus: string
  /** ★★☆ ✔ "57.2 deg" */
  FOV: string
  /** ☆☆☆ ✔ "100-0285" */
  FileNumber: string
  /** ☆☆☆   "Off, Did not fire" */
  Flash: string
  /** ☆☆☆   "Built-In Flash" */
  FlashType: string
  /** ★★★ ✔ "3.3 mm (35 mm equivalent: 33.0 mm)" */
  FocalLength35efl: string
  /** ☆☆☆ ✔ "54 m Above Sea Level" */
  GPSAltitude: string
  /** ☆☆☆ ✔ "2015:09:05 16:27:22.9Z" */
  GPSDateTime: string
  /** ☆☆☆ ✔ 40.86041667 */
  GPSLatitude: number
  /** ☆☆☆ ✔ 25.83040556 */
  GPSLongitude: number
  /** ☆☆☆ ✔ "40.86041667 N, 25.83040556 E" */
  GPSPosition: string
  /** ★★☆ ✔ "1.51 m" */
  HyperfocalDistance: string
  /** ☆☆☆ ✔ 141 */
  ISO: number
  /** ★★★ ✔ "8x8" */
  ImageSize: string
  /** ☆☆☆ ✔ "6.1 - 61.0 mm" */
  Lens: string
  /** ☆☆☆ ✔ "6.1 - 61.0 mm (35 mm equivalent: 39.8 - 398.4 mm)" */
  Lens35efl: string
  /** ☆☆☆ ✔ "Unknown 6-61mm" */
  LensID: string
  /** ☆☆☆ ✔ "105mm f/2.8 AF" */
  LensSpec: string
  /** ★★☆ ✔ 13.4 */
  LightValue: number
  /** ☆☆☆ ✔ "(Binary data 900042 bytes, use -b option to extract)" */
  MPImage3: string
  /** ★★★ ✔ 0.000064 */
  Megapixels: number
  /** ★☆☆ ✔ "(Binary data 347190 bytes, use -b option to extract)" */
  PreviewImage: string
  /** ☆☆☆ ✔ "1536x1024" */
  PreviewImageSize: string
  /** ☆☆☆ ✔ 2.294406 */
  RedBalance: number
  /** ☆☆☆   "Off" */
  RedEyeReduction: string
  /** ☆☆☆ ✔ "1 days 3:22:16" */
  RunTimeSincePowerUp: string
  /** ★★☆ ✔ 10 */
  ScaleFactor35efl: number
  /** ☆☆☆ ✔ "Program AE" */
  ShootingMode: string
  /** ☆☆☆   "1st-curtain sync" */
  ShutterCurtainHack: string
  /** ★★★ ✔ "1/604" */
  ShutterSpeed: string
  /** ☆☆☆ ✔ "2015:02:14 16:36:19.718" */
  SubSecCreateDate: string
  /** ☆☆☆ ✔ "2015:02:14 16:36:19.718" */
  SubSecDateTimeOriginal: string
  /** ☆☆☆ ✔ "2008:04:23 14:28:17.234" */
  SubSecModifyDate: string
  /** ★★★ ✔ "(Binary data 9462 bytes, use -b option to extract)" */
  ThumbnailImage: string
  /** ☆☆☆ ✔ "2338 1019 1019 1587" */
  WB_RGGBLevels: string
}

export interface MakerNotesTags {
  /** ☆☆☆   4.8 */
  AEAperture: number
  /** ☆☆☆   8 */
  AEApertureSteps: number
  /** ☆☆☆   "On" */
  AEBAutoCancel: string
  /** ☆☆☆ ✔ "+0.25" */
  AEBBracketValue: string
  /** ☆☆☆   "0,-,+" */
  AEBSequence: string
  /** ☆☆☆ ✔ "0,-,+/Enabled" */
  AEBSequenceAutoCancel: string
  /** ☆☆☆   0 */
  AEBXv: number
  /** ☆☆☆ ✔ "3F0.3" */
  AEBracketingSteps: string
  /** ☆☆☆   "1/85" */
  AEExposureTime: string
  /** ☆☆☆ ✔ "Off" */
  AELock: string
  /** ☆☆☆ ✔ "AE/AF Lock" */
  AELockButton: string
  /** ☆☆☆ ✔ "None" */
  AELockButtonPlusDials: string
  /** ☆☆☆   3.2 */
  AEMaxAperture: number
  /** ☆☆☆   3.4 */
  AEMaxAperture2: number
  /** ☆☆☆   "Multi-segment" */
  AEMeteringMode: string
  /** ☆☆☆   "8.6 8.8 9.4 9.1 9.1 9.0 9.1 8.9 9.3 9.1 9.1 8.8 9.1 8.6 10.0 9.0" */
  AEMeteringSegments: string
  /** ☆☆☆   23 */
  AEMinAperture: number
  /** ☆☆☆   "1/3862" */
  AEMinExposureTime: string
  /** ☆☆☆   "M, P or TAv" */
  AEProgramMode: string
  /** ☆☆☆   "Normal AE" */
  AESetting: string
  /** ☆☆☆   0 */
  AEXv: number
  /** ☆☆☆   200 */
  AE_ISO: number
  /** ☆☆☆ ✔ "Shutter/AF-On" */
  AFActivation: string
  /** ☆☆☆   0 */
  AFAdjustment: number
  /** ☆☆☆ ✔ 2 */
  AFAperture: number
  /** ☆☆☆ ✔ 42 */
  AFAreaHeight: number
  /** ☆☆☆ ✔ "37 37 37 37 37 37 37 37 37" */
  AFAreaHeights: string
  /** ☆☆☆ ✔ "Auto" */
  AFAreaMode: string
  /** ☆☆☆ ✔ 369 */
  AFAreaWidth: number
  /** ☆☆☆ ✔ "53 53 53 53 53 53 53 53 53" */
  AFAreaWidths: string
  /** ☆☆☆ ✔ "-54 0 53 -54 0 53 -54 0 53" */
  AFAreaXPositions: string
  /** ☆☆☆ ✔ "-38 -38 -38 0 0 0 38 38 38" */
  AFAreaYPositions: string
  /** ☆☆☆ ✔ "none" */
  AFAreas: string
  /** ☆☆☆ ✔ "Emits/Fires" */
  AFAssist: string
  /** ☆☆☆ ✔ "Emits" */
  AFAssistBeam: string
  /** ☆☆☆   "Enabled but Not Used" */
  AFAssistLamp: string
  /** ☆☆☆   46 */
  AFDefocus: number
  /** ☆☆☆ ✔ "Off" */
  AFFineTune: string
  /** ☆☆☆ ✔ 0 */
  AFFineTuneAdj: number
  /** ☆☆☆ ✔ "n/a" */
  AFFineTuneIndex: string
  /** ☆☆☆ ✔ 240 */
  AFImageHeight: number
  /** ☆☆☆ ✔ 320 */
  AFImageWidth: number
  /** ☆☆☆ ✔ "0100" */
  AFInfo2Version: string
  /** ☆☆☆   "2 ms" */
  AFIntegrationTime: string
  /** ☆☆☆ ✔ "Disable" */
  AFMicroAdjMode: string
  /** ☆☆☆ ✔ 0 */
  AFMicroAdjValue: number
  /** ☆☆☆ ✔ "Single Point" */
  AFMode: string
  /** ☆☆☆ ✔ "No Restrictions" */
  AFModeRestrictions: string
  /** ☆☆☆ ✔ "Auto AF point selection" */
  AFPoint: string
  /** ☆☆☆ ✔ "Single AF point" */
  AFPointActivationArea: string
  /** ☆☆☆ ✔ "Normal" */
  AFPointBrightness: string
  /** ☆☆☆   "Selected (constant)" */
  AFPointDisplayDuringFocus: string
  /** ☆☆☆ ✔ "On" */
  AFPointIllumination: string
  /** ☆☆☆   "Fixed Center" */
  AFPointMode: string
  /** ☆☆☆ ✔ "Auto" */
  AFPointSelected: string
  /** ☆☆☆   "Center" */
  AFPointSelected2: string
  /** ☆☆☆ ✔ "H=AF+Main/V=AF+Command" */
  AFPointSelection: string
  /** ☆☆☆ ✔ "45/Center AF point" */
  AFPointSpotMetering: string
  /** ★☆☆ ✔ 4 */
  AFPointsInFocus: number
  /** ☆☆☆ ✔ "Auto (A3,A4,A5,A6,A7,B5,B6,B7,B8)" */
  AFPointsInFocus1D: string
  /** ☆☆☆ ✔ "0,1,2,3,4,5,6" */
  AFPointsSelected: string
  /** ☆☆☆ ✔ "Center, Upper-right, Right, Lower-right, Upper-left, Far Left, Lower-middle, N… */
  AFPointsUsed: string
  /** ☆☆☆   -63 */
  AFPredictor: number
  /** ☆☆☆   "Standard" */
  AFResponse: string
  /** ☆☆☆   0 */
  AFResult: number
  /** ☆☆☆ ✔ "Not Ready" */
  AFSearch: string
  /** ☆☆☆ ✔ "Shooting not possible without focus" */
  AIServoContinuousShooting: string
  /** ☆☆☆ ✔ "Standard" */
  AIServoTrackingSensitivity: string
  /** ☆☆☆ ✔ "-1.008544087 -0.008590849015 -0.1717849637" */
  AccelerationVector: string
  /** ☆☆☆   "Off" */
  AddOriginalDecisionData: string
  /** ☆☆☆   " " */
  AdjustmentMode: string
  /** ☆☆☆ ✔ "Standard" */
  AmbienceSelection: string
  /** ☆☆☆ ✔ "Off" */
  ApertureLock: string
  /** ☆☆☆   "Prohibited" */
  ApertureRingUse: string
  /** ☆☆☆   8.6 */
  ApertureValue: number
  /** ☆☆☆ ✔ "Off; 0; 0; 0" */
  ArtFilter: string
  /** ☆☆☆ ✔ "Off; 0; 0; Partial Color 0; No Effect; 0; No Color Filter; 0; 0; 0; 0; 0; 0; 0… */
  ArtFilterEffect: string
  /** ☆☆☆ ✔ "0 0 4607 3455" */
  AspectFrame: string
  /** ☆☆☆ ✔ "3:2" */
  AspectRatio: string
  /** ☆☆☆ ✔ "Auto Bracketing" */
  AssignBktButton: string
  /** ☆☆☆ ✔ "None" */
  AssignMovieRecordButton: string
  /** ☆☆☆ ✔ "None" */
  AssignRemoteFnButton: string
  /** ☆☆☆   "No" */
  Audio: string
  /** ☆☆☆   "On" */
  AutoAperture: string
  /** ☆☆☆   "None" */
  AutoBracket: string
  /** ☆☆☆ ✔ "Flash/Speed" */
  AutoBracketModeM: string
  /** ☆☆☆ ✔ "0,-,+" */
  AutoBracketOrder: string
  /** ☆☆☆ ✔ "AE & Flash" */
  AutoBracketSet: string
  /** ☆☆☆ ✔ "Off" */
  AutoBracketing: string
  /** ☆☆☆ ✔ "On" */
  AutoDistortionControl: string
  /** ☆☆☆   "100%" */
  AutoDynamicRange: string
  /** ☆☆☆ ✔ "On" */
  AutoExposureBracketing: string
  /** ☆☆☆ ✔ 100 */
  AutoISO: number
  /** ☆☆☆ ✔ "Enable" */
  AutoLightingOptimizer: string
  /** ☆☆☆ ✔ "None" */
  AutoRotate: string
  /** ☆☆☆   "Off" */
  AuxiliaryLens: string
  /** ☆☆☆ ✔ "1024 1024 1024 1024" */
  AverageBlackLevel: string
  /** ☆☆☆   "Off" */
  BWMode: string
  /** ☆☆☆   "(not set)" */
  BabyAge: string
  /** ☆☆☆ ✔ 50 */
  BaseISO: number
  /** ☆☆☆ ✔ "MB-D12 First" */
  BatteryOrder: string
  /** ☆☆☆ ✔ "Off" */
  Beep: string
  /** ☆☆☆   "600 600 600 600" */
  BlackLevel: string
  /** ☆☆☆ ✔ "255 255 255 255" */
  BlackLevel2: string
  /** ☆☆☆ ✔ 0 */
  BlackMaskBottomBorder: number
  /** ☆☆☆ ✔ 0 */
  BlackMaskLeftBorder: number
  /** ☆☆☆ ✔ 0 */
  BlackMaskRightBorder: number
  /** ☆☆☆ ✔ 0 */
  BlackMaskTopBorder: number
  /** ☆☆☆   "129 128 127 128" */
  BlackPoint: string
  /** ☆☆☆   1.40625 */
  BlueBalance: number
  /** ☆☆☆ ✔ "None" */
  BlurWarning: string
  /** ☆☆☆   "Full" */
  BodyBatteryState: string
  /** ☆☆☆ ✔ 1.005 */
  BodyFirmwareVersion: number
  /** ☆☆☆ ✔ "Off" */
  BracketMode: string
  /** ☆☆☆ ✔ 0 */
  BracketShotNumber: number
  /** ☆☆☆ ✔ 0 */
  BracketValue: number
  /** ☆☆☆ ✔ 0 */
  Brightness: number
  /** ☆☆☆   9.39609375 */
  BrightnessValue: number
  /** ☆☆☆ ✔ 0 */
  BulbDuration: number
  /** ☆☆☆   "Off" */
  BurstMode: string
  /** ☆☆☆ ✔ "460727F2-20CF-4031-957B-7E04D567DF1F" */
  BurstUUID: string
  /** ☆☆☆ ✔ "6 fps" */
  CLModeShootingSpeed: string
  /** ☆☆☆   "1.00.00.05" */
  CPUFirmwareVersion: string
  /** ☆☆☆   " " */
  Calibration: string
  /** ☆☆☆ ✔ "OLYMPUS DIGITAL CAMERA         " */
  CameraID: string
  /** ☆☆☆   "Auto" */
  CameraISO: string
  /** ☆☆☆ ✔ "Horizontal (normal)" */
  CameraOrientation: string
  /** ☆☆☆ ✔ "0100" */
  CameraSettingsVersion: string
  /** ☆☆☆ ✔ "27 C" */
  CameraTemperature: string
  /** ☆☆☆ ✔ "DV Camera" */
  CameraType: string
  /** ☆☆☆ ✔ "E-M1" */
  CameraType2: string
  /** ☆☆☆ ✔ "Program AE" */
  CanonExposureMode: string
  /** ☆☆☆ ✔ "Firmware Version 2.01" */
  CanonFirmwareVersion: string
  /** ☆☆☆ ✔ "Auto" */
  CanonFlashMode: string
  /** ☆☆☆ ✔ 1840 */
  CanonImageHeight: number
  /** ☆☆☆ ✔ "Large" */
  CanonImageSize: string
  /** ☆☆☆ ✔ "IMG:iVIS DC50 JPEG" */
  CanonImageType: string
  /** ☆☆☆ ✔ 3264 */
  CanonImageWidth: number
  /** ☆☆☆ ✔ "DC50" */
  CanonModelID: string
  /** ☆☆☆   "(none)" */
  Categories: string
  /** ☆☆☆ ✔ "12 mm" */
  CenterWeightedAreaSize: string
  /** ☆☆☆ ✔ "Off" */
  ChromaticAberrationCorr: string
  /** ☆☆☆   "Off" */
  ChromaticAberrationCorrection: string
  /** ☆☆☆ ✔ "On" */
  ChromaticAberrationSetting: string
  /** ☆☆☆ ✔ 4 */
  Clarity: number
  /** ☆☆☆   "0 0 0" */
  ColorAdjustment: string
  /** ☆☆☆ ✔ "0224" */
  ColorBalanceVersion: string
  /** ☆☆☆   "24 1024 768 1024 16 256" */
  ColorControl: string
  /** ☆☆☆ ✔ "Color 0; 0; 29; Strength 0; -4; 3" */
  ColorCreatorEffect: string
  /** ☆☆☆ ✔ "5 (450D/1000D)" */
  ColorDataVersion: string
  /** ☆☆☆   "Off" */
  ColorEffect: string
  /** ☆☆☆ ✔ "Mode1" */
  ColorHue: string
  /** ☆☆☆ ✔ "368 -92 -20 -42 348 -50 10 -136 382" */
  ColorMatrix: string
  /** ☆☆☆ ✔ "Standard" */
  ColorMode: string
  /** ☆☆☆ ✔ "sRGB" */
  ColorSpace: string
  /** ☆☆☆ ✔ 4551 */
  ColorTempAsShot: number
  /** ☆☆☆ ✔ 4551 */
  ColorTempAuto: number
  /** ☆☆☆ ✔ 6000 */
  ColorTempCloudy: number
  /** ☆☆☆ ✔ 5210 */
  ColorTempCustom: number
  /** ☆☆☆ ✔ 5200 */
  ColorTempDaylight: number
  /** ☆☆☆ ✔ 6456 */
  ColorTempFlash: number
  /** ☆☆☆ ✔ 3901 */
  ColorTempFluorescent: number
  /** ☆☆☆ ✔ 5190 */
  ColorTempKelvin: number
  /** ☆☆☆ ✔ 4276 */
  ColorTempMeasured: number
  /** ☆☆☆ ✔ 4076 */
  ColorTempPC1: number
  /** ☆☆☆ ✔ 4076 */
  ColorTempPC2: number
  /** ☆☆☆ ✔ 4076 */
  ColorTempPC3: number
  /** ☆☆☆ ✔ 7000 */
  ColorTempShade: number
  /** ☆☆☆ ✔ 3200 */
  ColorTempTungsten: number
  /** ☆☆☆ ✔ 5200 */
  ColorTemperature: number
  /** ☆☆☆ ✔ "Normal" */
  ColorTone: string
  /** ☆☆☆ ✔ 0 */
  ColorToneAuto: number
  /** ☆☆☆ ✔ 0 */
  ColorToneFaithful: number
  /** ☆☆☆ ✔ 0 */
  ColorToneLandscape: number
  /** ☆☆☆ ✔ 0 */
  ColorToneNeutral: number
  /** ☆☆☆ ✔ 0 */
  ColorTonePortrait: number
  /** ☆☆☆ ✔ 0 */
  ColorToneStandard: number
  /** ☆☆☆ ✔ 0 */
  ColorToneUserDef1: number
  /** ☆☆☆ ✔ 0 */
  ColorToneUserDef2: number
  /** ☆☆☆ ✔ 0 */
  ColorToneUserDef3: number
  /** ☆☆☆ ✔ "Sub-command Dial" */
  CommandDialsApertureSetting: string
  /** ☆☆☆ ✔ "Autofocus Off, Exposure Off" */
  CommandDialsChangeMainSub: string
  /** ☆☆☆ ✔ "Off" */
  CommandDialsMenuAndPlayback: string
  /** ☆☆☆ ✔ "No" */
  CommandDialsReverseRotation: string
  /** ☆☆☆ ✔ "JPEG (old-style)" */
  Compression: string
  /** ☆☆☆ ✔ 4 */
  CompressionFactor: number
  /** ☆☆☆ ✔ "Continuous" */
  ContinuousDrive: string
  /** ★☆☆ ✔ "Normal" */
  Contrast: string
  /** ☆☆☆ ✔ 0 */
  ContrastAuto: number
  /** ☆☆☆ ✔ "Off" */
  ContrastDetectAF: string
  /** ☆☆☆   "0 0 0 0" */
  ContrastDetectAFArea: string
  /** ☆☆☆ ✔ "No" */
  ContrastDetectAFInFocus: string
  /** ☆☆☆ ✔ 0 */
  ContrastFaithful: number
  /** ☆☆☆ ✔ 0 */
  ContrastLandscape: number
  /** ☆☆☆   "Normal" */
  ContrastMode: string
  /** ☆☆☆ ✔ 0 */
  ContrastMonochrome: number
  /** ☆☆☆ ✔ 0 */
  ContrastNeutral: number
  /** ☆☆☆ ✔ 0 */
  ContrastPortrait: number
  /** ☆☆☆ ✔ "0 (min -5, max 5)" */
  ContrastSetting: string
  /** ☆☆☆ ✔ 0 */
  ContrastStandard: number
  /** ☆☆☆ ✔ 0 */
  ContrastUserDef1: number
  /** ☆☆☆ ✔ 0 */
  ContrastUserDef2: number
  /** ☆☆☆ ✔ 0 */
  ContrastUserDef3: number
  /** ☆☆☆ ✔ "n/a" */
  ControlMode: string
  /** ☆☆☆ ✔ "" */
  ConversionLens: string
  /** ☆☆☆   2176 */
  CoringFilter: number
  /** ☆☆☆   "" */
  CountryCode: string
  /** ☆☆☆ ✔ 0 */
  CropBottomMargin: number
  /** ☆☆☆ ✔ 3456 */
  CropHeight: number
  /** ☆☆☆ ✔ "Off (4320x2868 cropped to 4320x2868 at pixel 0,0)" */
  CropHiSpeed: string
  /** ☆☆☆ ✔ "8 0" */
  CropLeft: string
  /** ☆☆☆ ✔ 0 */
  CropLeftMargin: number
  /** ☆☆☆ ✔ 0 */
  CropRightMargin: number
  /** ☆☆☆ ✔ "8 0" */
  CropTop: string
  /** ☆☆☆ ✔ 0 */
  CropTopMargin: number
  /** ☆☆☆ ✔ 4608 */
  CropWidth: number
  /** ☆☆☆ ✔ 3456 */
  CroppedImageHeight: number
  /** ☆☆☆ ✔ 0 */
  CroppedImageLeft: number
  /** ☆☆☆ ✔ 0 */
  CroppedImageTop: number
  /** ☆☆☆ ✔ 5184 */
  CroppedImageWidth: number
  /** ☆☆☆   "0 0 1 0 0 1" */
  CustomControls: string
  /** ☆☆☆ ✔ "" */
  CustomPictureStyleFileName: string
  /** ☆☆☆ ✔ "0 (min -5, max 5)" */
  CustomSaturation: string
  /** ☆☆☆ ✔ "A" */
  CustomSettingsBank: string
  /** ☆☆☆ ✔ 6315 */
  CustomSettingsOffset: number
  /** ☆☆☆ ✔ "Matrix" */
  D810MeteringMode: string
  /** ☆☆☆   "1.00.00.00" */
  DSPFirmwareVersion: string
  /** ☆☆☆   "(Binary data 2540 bytes, use -b option to extract)" */
  DataDump: string
  /** ☆☆☆   8192 */
  DataScaling: number
  /** ☆☆☆   {"year":2007,"month":6,"day":6} */
  Date: ExifDate
  /** ☆☆☆ ✔ "Y/M/D" */
  DateDisplayFormat: string
  /** ☆☆☆   "Off" */
  DateStampMode: string
  /** ☆☆☆   {"year":1970,"month":1,"day":1,"hour":15,"minute":11,"second":20} */
  DateTimeOriginal: ExifDateTime
  /** ☆☆☆   "Off" */
  DateTimeStamp: string
  /** ☆☆☆ ✔ {"year":2013,"month":9,"day":7,"hour":13,"minute":1,"second":56,"tzoffsetMinute… */
  DateTimeUTC: ExifDateTime
  /** ☆☆☆ ✔ "Off" */
  DaylightSavings: string
  /** ☆☆☆ ✔ 19 */
  DeletedImageCount: number
  /** ☆☆☆   "Ho Chi Minh" */
  DestinationCity: string
  /** ☆☆☆   "No" */
  DestinationDST: string
  /** ☆☆☆ ✔ 100 */
  DevelopmentDynamicRange: number
  /** ☆☆☆   "Compact Digital Camera" */
  DeviceType: string
  /** ☆☆☆   "Normal" */
  DialDirectionTvAv: string
  /** ☆☆☆ ✔ 0 */
  DigitalGain: number
  /** ★☆☆ ✔ "None" */
  DigitalZoom: string
  /** ☆☆☆ ✔ 100 */
  DirectoryIndex: number
  /** ☆☆☆ ✔ 806 */
  DirectoryNumber: number
  /** ☆☆☆   3.9 */
  DisplayAperture: number
  /** ☆☆☆ ✔ "Applied" */
  DistortionCorrection: string
  /** ☆☆☆ ✔ "On" */
  DistortionCorrection2: string
  /** ☆☆☆ ✔ "Single Shot" */
  DriveMode: string
  /** ☆☆☆   "Single-frame" */
  DriveMode2: string
  /** ☆☆☆ ✔ "(Binary data 1024 bytes, use -b option to extract)" */
  DustRemovalData: string
  /** ☆☆☆ ✔ "Off" */
  DynamicAreaAFDisplay: string
  /** ☆☆☆ ✔ "Standard" */
  DynamicRange: string
  /** ☆☆☆   "Off; 0; 0; 0" */
  DynamicRangeExpansion: string
  /** ☆☆☆ ✔ "Manual" */
  DynamicRangeSetting: string
  /** ☆☆☆ ✔ "Evaluative" */
  ETTLII: string
  /** ☆☆☆   "1/2 EV Steps" */
  EVSteps: string
  /** ☆☆☆ ✔ "Off" */
  EasyExposureCompensation: string
  /** ☆☆☆ ✔ "Manual" */
  EasyMode: string
  /** ☆☆☆   10 */
  EffectiveLV: number
  /** ☆☆☆ ✔ 2 */
  EffectiveMaxAperture: number
  /** ☆☆☆   42 */
  Enhancer: number
  /** ☆☆☆ ✔ "0100" */
  EquipmentVersion: string
  /** ☆☆☆ ✔ "93.1 mm" */
  ExitPupilPosition: string
  /** ☆☆☆   0.5 */
  ExposureBracketStepSize: number
  /** ☆☆☆ ✔ 0 */
  ExposureBracketValue: number
  /** ☆☆☆ ✔ "1/3 EV" */
  ExposureCompStepSize: string
  /** ☆☆☆ ✔ 0 */
  ExposureCompensation: number
  /** ☆☆☆ ✔ "1/3 EV" */
  ExposureControlStepSize: string
  /** ☆☆☆ ✔ 1 */
  ExposureCount: number
  /** ☆☆☆ ✔ "Off" */
  ExposureDelayMode: string
  /** ☆☆☆ ✔ 0 */
  ExposureDifference: number
  /** ☆☆☆ ✔ "1/3 Stop" */
  ExposureLevelIncrements: string
  /** ☆☆☆ ✔ "Landscape" */
  ExposureMode: string
  /** ☆☆☆ ✔ 0 */
  ExposureShift: number
  /** ☆☆☆ ✔ "1/64" */
  ExposureTime: string
  /** ☆☆☆ ✔ 0 */
  ExposureTuning: number
  /** ☆☆☆ ✔ "Good" */
  ExposureWarning: string
  /** ☆☆☆ ✔ "Off" */
  ExtendedWBDetect: string
  /** ☆☆☆ ✔ "None" */
  Extender: string
  /** ☆☆☆ ✔ 0 */
  ExtenderFirmwareVersion: number
  /** ☆☆☆ ✔ "" */
  ExtenderModel: string
  /** ☆☆☆ ✔ "" */
  ExtenderSerialNumber: string
  /** ☆☆☆   "Not attached" */
  ExtenderStatus: string
  /** ☆☆☆ ✔ "Off" */
  ExternalFlash: string
  /** ☆☆☆ ✔ "Bounce or Off" */
  ExternalFlashBounce: string
  /** ☆☆☆   0 */
  ExternalFlashCompensation: number
  /** ☆☆☆ ✔ 0 */
  ExternalFlashExposureComp: number
  /** ☆☆☆ ✔ "n/a" */
  ExternalFlashFirmware: string
  /** ☆☆☆ ✔ "(none)" */
  ExternalFlashFlags: string
  /** ☆☆☆   0 */
  ExternalFlashGValue: number
  /** ☆☆☆   0 */
  ExternalFlashMode: number
  /** ☆☆☆ ✔ "n/a" */
  ExternalFlashReadyState: string
  /** ☆☆☆ ✔ "Flash Not Attached" */
  ExternalFlashStatus: string
  /** ☆☆☆ ✔ 0 */
  ExternalFlashZoom: number
  /** ☆☆☆ ✔ 2.9 */
  FNumber: number
  /** ☆☆☆   "12 -54" */
  Face1Position: string
  /** ☆☆☆   "On (5 faces max); 0 faces detected; 0" */
  FaceDetect: string
  /** ☆☆☆ ✔ "(Binary data 383 bytes, use -b option to extract)" */
  FaceDetectArea: string
  /** ☆☆☆ ✔ "0 0 0 0 0 0 0 0 0 0 0 0" */
  FaceDetectFrameCrop: string
  /** ☆☆☆ ✔ "320 240" */
  FaceDetectFrameSize: string
  /** ☆☆☆   "0 0" */
  FacePosition: string
  /** ☆☆☆   "643 482 1393 1232" */
  FacePositions: string
  /** ☆☆☆   "Off" */
  FaceRecognition: string
  /** ☆☆☆   35 */
  FaceWidth: number
  /** ☆☆☆ ✔ 0 */
  FacesDetected: number
  /** ☆☆☆   "JPEG (lossy/non-quantization toggled)" */
  FileFormat: string
  /** ☆☆☆ ✔ 285 */
  FileIndex: number
  /** ☆☆☆ ✔ "0100" */
  FileInfoVersion: string
  /** ☆☆☆ ✔ "196-9624" */
  FileNumber: string
  /** ☆☆☆ ✔ "Enable" */
  FillFlashAutoReduction: string
  /** ☆☆☆ ✔ "F0/Standard (Provia)" */
  FilmMode: string
  /** ☆☆☆ ✔ "None" */
  FilterEffect: string
  /** ☆☆☆ ✔ "n/a" */
  FilterEffectAuto: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectMonochrome: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectUserDef1: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectUserDef2: string
  /** ☆☆☆ ✔ "None" */
  FilterEffectUserDef3: string
  /** ☆☆☆ ✔ "Off" */
  FinderDisplayDuringExposure: string
  /** ☆☆☆   "Off" */
  FineSharpness: string
  /** ☆☆☆ ✔ 0 */
  FineTuneOptCenterWeighted: number
  /** ☆☆☆ ✔ 0 */
  FineTuneOptHighlightWeighted: number
  /** ☆☆☆ ✔ 0 */
  FineTuneOptMatrixMetering: number
  /** ☆☆☆ ✔ 0 */
  FineTuneOptSpotMetering: number
  /** ☆☆☆   "73" */
  Firmware: string
  /** ☆☆☆   "1.00 rev 3.00" */
  FirmwareRevision: string
  /** ☆☆☆ ✔ "1.0.3" */
  FirmwareVersion: string
  /** ☆☆☆ ✔ "Off" */
  FisheyeFilter: string
  /** ☆☆☆ ✔ 0 */
  FlashActivity: number
  /** ☆☆☆ ✔ "n/a" */
  FlashBatteryLevel: string
  /** ☆☆☆   0 */
  FlashBias: number
  /** ☆☆☆ ✔ "E-TTL, Built-in" */
  FlashBits: string
  /** ☆☆☆   0 */
  FlashChargeLevel: number
  /** ☆☆☆   "None" */
  FlashColorFilter: string
  /** ☆☆☆ ✔ "Off" */
  FlashCommanderMode: string
  /** ☆☆☆ ✔ 0 */
  FlashCompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashControlMode: string
  /** ☆☆☆   "Unknown (0 0)" */
  FlashDevice: string
  /** ☆☆☆ ✔ 0 */
  FlashExposureBracketValue: number
  /** ★☆☆ ✔ 0 */
  FlashExposureComp: number
  /** ☆☆☆   0 */
  FlashExposureComp3: number
  /** ☆☆☆   "-2/3" */
  FlashExposureComp4: string
  /** ☆☆☆ ✔ "Entire frame" */
  FlashExposureCompArea: string
  /** ☆☆☆ ✔ "Off" */
  FlashExposureLock: string
  /** ☆☆☆   true */
  FlashFired: boolean
  /** ☆☆☆ ✔ 0 */
  FlashFirmwareVersion: number
  /** ☆☆☆ ✔ 0 */
  FlashGNDistance: number
  /** ☆☆☆ ✔ 0 */
  FlashGroupACompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashGroupAControlMode: string
  /** ☆☆☆ ✔ 0 */
  FlashGroupBCompensation: number
  /** ☆☆☆ ✔ "Off" */
  FlashGroupBControlMode: string
  /** ☆☆☆   0 */
  FlashGroupCCompensation: number
  /** ☆☆☆   "Off" */
  FlashGroupCControlMode: string
  /** ☆☆☆ ✔ 8.46875 */
  FlashGuideNumber: number
  /** ☆☆☆ ✔ "0100" */
  FlashInfoVersion: string
  /** ☆☆☆ ✔ "n/a (x4)" */
  FlashIntensity: string
  /** ☆☆☆   "Off" */
  FlashMeteringMode: string
  /** ☆☆☆   "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" */
  FlashMeteringSegments: string
  /** ☆☆☆ ✔ "Flash Off" */
  FlashMode: string
  /** ☆☆☆ ✔ "None" */
  FlashModel: string
  /** ☆☆☆   "Normal" */
  FlashOptions: string
  /** ☆☆☆ ✔ 175 */
  FlashOutput: number
  /** ☆☆☆ ✔ "Off" */
  FlashRemoteControl: string
  /** ☆☆☆ ✔ "" */
  FlashSerialNumber: string
  /** ☆☆☆ ✔ "" */
  FlashSetting: string
  /** ☆☆☆ ✔ "1/60 s" */
  FlashShutterSpeed: string
  /** ☆☆☆ ✔ "None" */
  FlashSource: string
  /** ☆☆☆ ✔ "1/250 s" */
  FlashSyncSpeed: string
  /** ☆☆☆ ✔ "Auto" */
  FlashSyncSpeedAv: string
  /** ☆☆☆ ✔ "" */
  FlashType: string
  /** ☆☆☆ ✔ "15.53 mm" */
  FocalLength: string
  /** ☆☆☆ ✔ "21.6 mm" */
  FocalPlaneDiagonal: string
  /** ☆☆☆ ✔ "5.44 mm" */
  FocalPlaneXSize: string
  /** ☆☆☆ ✔ "4.06 mm" */
  FocalPlaneYSize: string
  /** ☆☆☆ ✔ "Zoom" */
  FocalType: string
  /** ☆☆☆ ✔ "100/mm" */
  FocalUnits: string
  /** ☆☆☆ ✔ "Continuous" */
  FocusContinuous: string
  /** ☆☆☆ ✔ "2.11 m" */
  FocusDistance: string
  /** ☆☆☆ ✔ "0 m" */
  FocusDistanceLower: string
  /** ☆☆☆ ✔ "65.53 m" */
  FocusDistanceUpper: string
  /** ☆☆☆ ✔ "0100" */
  FocusInfoVersion: string
  /** ★☆☆ ✔ "Single" */
  FocusMode: string
  /** ☆☆☆   "AF-S" */
  FocusMode2: string
  /** ☆☆☆ ✔ "1824 1368" */
  FocusPixel: string
  /** ☆☆☆ ✔ "No Wrap" */
  FocusPointWrap: string
  /** ☆☆☆ ✔ "0x11" */
  FocusPosition: string
  /** ☆☆☆ ✔ "AF Used; 64" */
  FocusProcess: string
  /** ☆☆☆ ✔ "Auto" */
  FocusRange: string
  /** ☆☆☆   4 */
  FocusRangeIndex: number
  /** ☆☆☆   "AF" */
  FocusSetting: string
  /** ☆☆☆ ✔ 286 */
  FocusStepCount: number
  /** ☆☆☆ ✔ 0 */
  FocusStepInfinity: number
  /** ☆☆☆ ✔ 0 */
  FocusStepNear: number
  /** ☆☆☆ ✔ "3 (Normal)" */
  FocusTrackingLockOn: string
  /** ☆☆☆ ✔ "Good" */
  FocusWarning: string
  /** ☆☆☆ ✔ "Ec-CIV" */
  FocusingScreen: string
  /** ☆☆☆   1 */
  FrameNumber: number
  /** ☆☆☆ ✔ "Off" */
  FujiFlashMode: string
  /** ☆☆☆ ✔ "Virtual Horizon" */
  FuncButton: string
  /** ☆☆☆ ✔ "None" */
  FuncButtonPlusDials: string
  /** ☆☆☆ ✔ 256 */
  GainBase: number
  /** ☆☆☆ ✔ "Normal; User-Selected" */
  Gradation: string
  /** ☆☆☆ ✔ "Off" */
  GrainyBWFilter: string
  /** ☆☆☆ ✔ "On" */
  GridDisplay: string
  /** ☆☆☆ ✔ "Squares" */
  GroupAreaAFIllumination: string
  /** ☆☆☆ ✔ "Off" */
  HDR: string
  /** ☆☆☆ ✔ "Natural" */
  HDREffect: string
  /** ☆☆☆ ✔ "Unknown (2)" */
  HDRImageType: string
  /** ☆☆☆ ✔ "0200" */
  HDRInfoVersion: string
  /** ☆☆☆ ✔ "Auto" */
  HDRLevel: string
  /** ☆☆☆ ✔ "n/a" */
  HDRLevel2: string
  /** ☆☆☆ ✔ "Off" */
  HDRSmoothing: string
  /** ☆☆☆ ✔ "Off" */
  HighISONoiseReduction: string
  /** ☆☆☆   0 */
  HighLowKeyAdj: number
  /** ☆☆☆   0 */
  Highlight: number
  /** ☆☆☆ ✔ "Normal" */
  HighlightTone: string
  /** ☆☆☆ ✔ "Disable" */
  HighlightTonePriority: string
  /** ☆☆☆   "London" */
  HometownCity: string
  /** ☆☆☆   "Yes" */
  HometownDST: string
  /** ☆☆☆ ✔ "None" */
  Hue: string
  /** ☆☆☆ ✔ 3 */
  HueAdjustment: number
  /** ☆☆☆ ✔ 100 */
  ISO: number
  /** ☆☆☆ ✔ 100 */
  ISO2: number
  /** ☆☆☆ ✔ "ISO 12800" */
  ISOAutoHiLimit: string
  /** ☆☆☆ ✔ "Auto" */
  ISOAutoShutterTime: string
  /** ☆☆☆ ✔ "Show Frame Count" */
  ISODisplay: string
  /** ☆☆☆ ✔ "On" */
  ISOExpansion: string
  /** ☆☆☆ ✔ "Off" */
  ISOExpansion2: string
  /** ☆☆☆   200 */
  ISOFloor: number
  /** ☆☆☆   "Auto" */
  ISOSelection: string
  /** ☆☆☆ ✔ 250 */
  ISOSetting: number
  /** ☆☆☆ ✔ "No" */
  ISOSpeedExpansion: string
  /** ☆☆☆   "1/3 Stop" */
  ISOSpeedIncrements: string
  /** ☆☆☆ ✔ "1/3 EV" */
  ISOStepSize: string
  /** ☆☆☆   100 */
  ISOValue: number
  /** ☆☆☆   "Auto" */
  ImageAdjustment: string
  /** ☆☆☆ ✔ "0 0 4288 2848" */
  ImageBoundary: string
  /** ☆☆☆ ✔ 1 */
  ImageCount: number
  /** ☆☆☆ ✔ 4996902 */
  ImageDataSize: number
  /** ☆☆☆   0 */
  ImageEditCount: number
  /** ☆☆☆   "None" */
  ImageEditing: string
  /** ☆☆☆ ✔ "Original Image" */
  ImageGeneration: string
  /** ☆☆☆   "Normal" */
  ImageOptimization: string
  /** ☆☆☆   "" */
  ImageProcessing: string
  /** ☆☆☆ ✔ "0112" */
  ImageProcessingVersion: string
  /** ☆☆☆   "High" */
  ImageQuality: string
  /** ☆☆☆   "SQ (5)" */
  ImageQuality2: string
  /** ☆☆☆ ✔ "4 s" */
  ImageReviewMonitorOffTime: string
  /** ☆☆☆ ✔ "On" */
  ImageStabilization: string
  /** ☆☆☆   "Bright" */
  ImageTone: string
  /** ☆☆☆   "25c584939cdf2fe47ac7af920c3ef487" */
  ImageUniqueID: string
  /** ☆☆☆   "Off" */
  IntelligentContrast: string
  /** ☆☆☆ ✔ "Off" */
  InternalFlash: string
  /** ☆☆☆   75 */
  InternalFlashTable: number
  /** ☆☆☆ ✔ "K0027622" */
  InternalSerialNumber: string
  /** ☆☆☆ ✔ 7 */
  JPEGQuality: number
  /** ☆☆☆ ✔ "Off" */
  KeystoneCompensation: string
  /** ☆☆☆ ✔ "Vertical" */
  KeystoneDirection: string
  /** ☆☆☆ ✔ "0 -20 20" */
  KeystoneValue: string
  /** ☆☆☆   1932 */
  KodakImageHeight: number
  /** ☆☆☆   2576 */
  KodakImageWidth: number
  /** ☆☆☆   "C360    " */
  KodakModel: string
  /** ☆☆☆ ✔ "Display" */
  LCDDisplayAtPowerOn: string
  /** ☆☆☆ ✔ "Off" */
  LCDIllumination: string
  /** ☆☆☆ ✔ "Remain. shots/File no." */
  LCDPanels: string
  /** ☆☆☆ ✔ "105mm f/2.8" */
  Lens: string
  /** ☆☆☆ ✔ "AF Stop" */
  LensAFStopButton: string
  /** ☆☆☆   "4.0 to 22" */
  LensApertureRange: string
  /** ☆☆☆ ✔ "0201" */
  LensDataVersion: string
  /** ☆☆☆   "-30641 21134 32382 25674 17516 32364" */
  LensDistortionParams: string
  /** ☆☆☆ ✔ 7 */
  LensFStops: number
  /** ☆☆☆ ✔ "Ver.02" */
  LensFirmwareVersion: string
  /** ☆☆☆   "28.1 mm" */
  LensFocalLength: string
  /** ☆☆☆   "14 to 14" */
  LensFocalRange: string
  /** ☆☆☆ ✔ "AF Lock Only" */
  LensFocusFunctionButtons: string
  /** ☆☆☆ ✔ 129 */
  LensIDNumber: number
  /** ☆☆☆ ✔ "EF-S18-55mm f/3.5-5.6 IS" */
  LensModel: string
  /** ☆☆☆ ✔ "0xc041" */
  LensProperties: string
  /** ☆☆☆ ✔ "00002042bc" */
  LensSerialNumber: string
  /** ☆☆☆ ✔ "n/a" */
  LensType: string
  /** ☆☆☆   0 */
  LightCondition: number
  /** ☆☆☆   18 */
  LightReading: number
  /** ☆☆☆ ✔ "Natural" */
  LightSource: string
  /** ☆☆☆ ✔ "LCD Backlight" */
  LightSwitch: string
  /** ☆☆☆ ✔ "No Restrictions" */
  LimitAFAreaModeSelection: string
  /** ☆☆☆ ✔ 10000 */
  LinearityUpperMargin: number
  /** ☆☆☆ ✔ "Enable" */
  LiveViewButtonOptions: string
  /** ☆☆☆ ✔ "10 min" */
  LiveViewMonitorOffTime: string
  /** ☆☆☆ ✔ "Off" */
  LiveViewShooting: string
  /** ☆☆☆   "" */
  Location: string
  /** ☆☆☆   "0100" */
  LocationInfoVersion: string
  /** ☆☆☆ ✔ "Off" */
  LongExposureNoiseReduction: string
  /** ☆☆☆ ✔ "Off" */
  LongExposureNoiseReduction2: string
  /** ☆☆☆ ✔ 134 */
  MCUVersion: number
  /** ☆☆☆ ✔ "Off" */
  Macro: string
  /** ☆☆☆ ✔ "Off" */
  MacroLED: string
  /** ☆☆☆ ✔ "Unknown (0)" */
  MacroMode: string
  /** ☆☆☆   "Off; 1280; 0; 0" */
  MagicFilter: string
  /** ☆☆☆ ✔ "Image playback only" */
  MagnifiedView: string
  /** ☆☆☆ ✔ 1.01 */
  MakerNoteVersion: number
  /** ☆☆☆ ✔ "0 kPa" */
  ManometerPressure: string
  /** ☆☆☆ ✔ "0 m, 0 ft" */
  ManometerReading: string
  /** ☆☆☆ ✔ "Off" */
  ManualFlash: string
  /** ☆☆☆ ✔ "n/a" */
  ManualFlashOutput: string
  /** ☆☆☆ ✔ "n/a (x4)" */
  ManualFlashStrength: string
  /** ☆☆☆   "undef" */
  ManualFocusDistance: string
  /** ☆☆☆ ✔ "Tv=Main/Av=Control" */
  ManualTv: string
  /** ☆☆☆   {"year":2003,"month":8,"day":5} */
  ManufactureDate: ExifDate
  /** ☆☆☆ ✔ "Face Detection On" */
  MatrixMetering: string
  /** ☆☆☆ ✔ 2.9 */
  MaxAperture: number
  /** ☆☆☆ ✔ 4.5 */
  MaxApertureAtMaxFocal: number
  /** ☆☆☆ ✔ 3.5 */
  MaxApertureAtMinFocal: number
  /** ☆☆☆ ✔ 100 */
  MaxContinuousRelease: number
  /** ☆☆☆ ✔ "0 0 0" */
  MaxFaces: string
  /** ☆☆☆ ✔ "61 mm" */
  MaxFocalLength: string
  /** ☆☆☆ ✔ 5 */
  MeasuredEV: number
  /** ☆☆☆ ✔ 12.625 */
  MeasuredEV2: number
  /** ☆☆☆ ✔ "471 1024 1024 581" */
  MeasuredRGGB: string
  /** ☆☆☆ ✔ "28263 52181 52475 22264" */
  MeasuredRGGBData: string
  /** ☆☆☆ ✔ 0 */
  MemoryCardNumber: number
  /** ☆☆☆ ✔ "1 min" */
  MenuMonitorOffTime: string
  /** ★☆☆ ✔ "Evaluative" */
  MeteringMode: string
  /** ☆☆☆   "Multi-segment" */
  MeteringMode2: string
  /** ☆☆☆ ✔ 6.9 */
  MinAperture: number
  /** ☆☆☆ ✔ "6.1 mm" */
  MinFocalLength: string
  /** ☆☆☆   "0.49-0.50 m" */
  MinFocusDistance: string
  /** ☆☆☆ ✔ "Off" */
  MiniatureFilter: string
  /** ☆☆☆ ✔ "Horizontal" */
  MiniatureFilterOrientation: string
  /** ☆☆☆ ✔ 0 */
  MiniatureFilterParameter: number
  /** ☆☆☆ ✔ 0 */
  MiniatureFilterPosition: number
  /** ☆☆☆ ✔ "Disable" */
  MirrorLockup: string
  /** ☆☆☆ ✔ "On" */
  ModelingFlash: string
  /** ☆☆☆ ✔ "Off" */
  ModifiedSaturation: string
  /** ☆☆☆   "None" */
  MonochromeFilterEffect: string
  /** ☆☆☆   "None" */
  MonochromeToning: string
  /** ☆☆☆   "11:19" */
  MonthDayCreated: string
  /** ☆☆☆ ✔ "AE/AF Lock" */
  MovieAELockButtonAssignment: string
  /** ☆☆☆ ✔ "None" */
  MovieFunctionButton: string
  /** ☆☆☆ ✔ "Index Marking" */
  MoviePreviewButton: string
  /** ☆☆☆ ✔ "Take Photo" */
  MovieShutterButton: string
  /** ☆☆☆ ✔ "Off" */
  MultiExposureAutoGain: string
  /** ☆☆☆ ✔ "Off" */
  MultiExposureMode: string
  /** ☆☆☆ ✔ 0 */
  MultiExposureShots: number
  /** ☆☆☆ ✔ "0100" */
  MultiExposureVersion: string
  /** ☆☆☆ ✔ "Do Nothing" */
  MultiSelector: string
  /** ☆☆☆ ✔ "Reset" */
  MultiSelectorLiveView: string
  /** ☆☆☆ ✔ "Thumbnail On/Off" */
  MultiSelectorPlaybackMode: string
  /** ☆☆☆ ✔ "Select Center Focus Point (Reset)" */
  MultiSelectorShootMode: string
  /** ☆☆☆ ✔ "Off; 1" */
  MultipleExposureMode: string
  /** ☆☆☆   "Off" */
  MultipleExposureSet: string
  /** ☆☆☆   "Off" */
  MyColorMode: string
  /** ☆☆☆ ✔ "n/a" */
  NDFilter: string
  /** ☆☆☆   "n/a (JPEG)" */
  NEFBitDepth: string
  /** ☆☆☆   "OTHER" */
  NikonCaptureVersion: string
  /** ☆☆☆ ✔ "Enable Release" */
  NoMemoryCard: string
  /** ☆☆☆ ✔ "Off" */
  NoiseFilter: string
  /** ☆☆☆ ✔ "n/a" */
  NoiseReduction: string
  /** ☆☆☆ ✔ "(none)" */
  NoiseReduction2: string
  /** ☆☆☆   3.4 */
  NominalMaxAperture: number
  /** ☆☆☆   23 */
  NominalMinAperture: number
  /** ☆☆☆ ✔ 14582 */
  NormalWhiteLevel: number
  /** ☆☆☆ ✔ 9 */
  NumAFPoints: number
  /** ☆☆☆   1536 */
  OlympusImageHeight: number
  /** ☆☆☆   2048 */
  OlympusImageWidth: number
  /** ☆☆☆   "Off" */
  OneTouchWB: string
  /** ☆☆☆   1 */
  OpticalZoom: number
  /** ☆☆☆ ✔ "n/a" */
  OpticalZoomCode: string
  /** ☆☆☆   "Standard" */
  OpticalZoomMode: string
  /** ☆☆☆ ✔ 0 */
  OriginalDecisionDataOffset: number
  /** ☆☆☆ ✔ 3168 */
  OriginalImageHeight: number
  /** ☆☆☆ ✔ 4752 */
  OriginalImageWidth: number
  /** ☆☆☆ ✔ "" */
  OwnerName: string
  /** ☆☆☆ ✔ "Off" */
  PF0CustomFuncRegistration: string
  /** ☆☆☆ ✔ "Off" */
  PF10RetainProgramShift: string
  /** ☆☆☆ ✔ "Off" */
  PF13DrivePriority: string
  /** ☆☆☆ ✔ "Off" */
  PF14DisableFocusSearch: string
  /** ☆☆☆ ✔ "Off" */
  PF15DisableAFAssistBeam: string
  /** ☆☆☆ ✔ "Off" */
  PF16AutoFocusPointShoot: string
  /** ☆☆☆ ✔ "Off" */
  PF17DisableAFPointSel: string
  /** ☆☆☆ ✔ "Off" */
  PF18EnableAutoAFPointSel: string
  /** ☆☆☆ ✔ "Off" */
  PF19ContinuousShootSpeed: string
  /** ☆☆☆ ✔ 3 */
  PF19ShootingSpeedHigh: number
  /** ☆☆☆ ✔ 8 */
  PF19ShootingSpeedLow: number
  /** ☆☆☆ ✔ "Off" */
  PF1DisableShootingModes: string
  /** ☆☆☆ ✔ 244 */
  PF1Value: number
  /** ☆☆☆ ✔ "Off" */
  PF20LimitContinousShots: string
  /** ☆☆☆ ✔ 99 */
  PF20MaxContinousShots: number
  /** ☆☆☆ ✔ "Off" */
  PF21EnableQuietOperation: string
  /** ☆☆☆ ✔ 256 */
  PF23FELockTime: number
  /** ☆☆☆ ✔ 32 */
  PF23PostReleaseTime: number
  /** ☆☆☆ ✔ "Off" */
  PF23SetTimerLengths: string
  /** ☆☆☆ ✔ 96 */
  PF23ShutterButtonTime: number
  /** ☆☆☆ ✔ "Off" */
  PF24LightLCDDuringBulb: string
  /** ☆☆☆ ✔ 16 */
  PF25AEMode: number
  /** ☆☆☆ ✔ 2 */
  PF25AFMode: number
  /** ☆☆☆ ✔ 255 */
  PF25AFPointSel: number
  /** ☆☆☆ ✔ 1 */
  PF25ColorMatrix: number
  /** ☆☆☆ ✔ "Off" */
  PF25DefaultClearSettings: string
  /** ☆☆☆ ✔ 4 */
  PF25DriveMode: number
  /** ☆☆☆ ✔ 16 */
  PF25ImageSize: number
  /** ☆☆☆ ✔ 32 */
  PF25MeteringMode: number
  /** ☆☆☆ ✔ 129 */
  PF25Parameters: number
  /** ☆☆☆ ✔ 0 */
  PF25WBMode: number
  /** ☆☆☆ ✔ "Off" */
  PF26ShortenReleaseLag: string
  /** ☆☆☆ ✔ "Off" */
  PF27ReverseDialRotation: string
  /** ☆☆☆ ✔ 2 */
  PF27Value: number
  /** ☆☆☆ ✔ "Off" */
  PF28NoQuickDialExpComp: string
  /** ☆☆☆ ✔ "Off" */
  PF29QuickDialSwitchOff: string
  /** ☆☆☆ ✔ "Off" */
  PF2DisableMeteringModes: string
  /** ☆☆☆ ✔ 240 */
  PF2Value: number
  /** ☆☆☆ ✔ "Off" */
  PF30EnlargementMode: string
  /** ☆☆☆ ✔ "Off" */
  PF31OriginalDecisionData: string
  /** ☆☆☆ ✔ "Off" */
  PF3ManualExposureMetering: string
  /** ☆☆☆ ✔ 16 */
  PF3Value: number
  /** ☆☆☆ ✔ "Off" */
  PF4ExposureTimeLimits: string
  /** ☆☆☆ ✔ 31.3 */
  PF4ExposureTimeMax: number
  /** ☆☆☆ ✔ "1/8389" */
  PF4ExposureTimeMin: string
  /** ☆☆☆ ✔ "Off" */
  PF5ApertureLimits: string
  /** ☆☆☆ ✔ 1 */
  PF5ApertureMax: number
  /** ☆☆☆ ✔ 91 */
  PF5ApertureMin: number
  /** ☆☆☆ ✔ "Off" */
  PF6PresetShootingModes: string
  /** ☆☆☆ ✔ "Off" */
  PF7BracketContinuousShoot: string
  /** ☆☆☆ ✔ 3 */
  PF8BracketShots: number
  /** ☆☆☆ ✔ "Off" */
  PF8SetBracketShots: string
  /** ☆☆☆ ✔ "Off" */
  PF9ChangeBracketSequence: string
  /** ☆☆☆   0 */
  POILevel: number
  /** ☆☆☆ ✔ "Off" */
  PaintingFilter: string
  /** ☆☆☆   "0200" */
  PanasonicExifVersion: string
  /** ☆☆☆ ✔ "Off" */
  PanoramaMode: string
  /** ☆☆☆   "Full" */
  PentaxImageSize: string
  /** ☆☆☆   "*ist D" */
  PentaxModelID: string
  /** ☆☆☆   2 */
  PentaxModelType: number
  /** ☆☆☆   "6.0.0.0" */
  PentaxVersion: string
  /** ☆☆☆ ✔ "1023 1024 1023 1024" */
  PerChannelBlackLevel: string
  /** ☆☆☆ ✔ "On" */
  PeripheralIlluminationCorr: string
  /** ☆☆☆ ✔ "Off" */
  PeripheralLighting: string
  /** ☆☆☆ ✔ "Off" */
  PeripheralLightingSetting: string
  /** ☆☆☆ ✔ 0 */
  PeripheralLightingValue: number
  /** ☆☆☆ ✔ "Off" */
  PhaseDetectAF: string
  /** ☆☆☆ ✔ "Off" */
  PhotoEffect: string
  /** ☆☆☆ ✔ "Full Control" */
  PictureControlAdjust: string
  /** ☆☆☆ ✔ "Landscape" */
  PictureControlBase: string
  /** ☆☆☆ ✔ "Landscape" */
  PictureControlName: string
  /** ☆☆☆ ✔ "Normal" */
  PictureControlQuickAdjust: string
  /** ☆☆☆ ✔ "0200" */
  PictureControlVersion: string
  /** ☆☆☆ ✔ "Program AE" */
  PictureMode: string
  /** ☆☆☆   "Program AE" */
  PictureMode2: string
  /** ☆☆☆ ✔ "n/a" */
  PictureModeBWFilter: string
  /** ☆☆☆ ✔ "0 (min -2, max 2)" */
  PictureModeContrast: string
  /** ☆☆☆ ✔ "Standard" */
  PictureModeEffect: string
  /** ☆☆☆ ✔ "0 (min -2, max 2)" */
  PictureModeSaturation: string
  /** ☆☆☆ ✔ "0 (min -2, max 2)" */
  PictureModeSharpness: string
  /** ☆☆☆ ✔ "n/a" */
  PictureModeTone: string
  /** ☆☆☆ ✔ "None" */
  PictureStyle: string
  /** ☆☆☆ ✔ "None; None; None" */
  PictureStylePC: string
  /** ☆☆☆ ✔ "Standard; Standard; Standard" */
  PictureStyleUserDef: string
  /** ☆☆☆ ✔ "+0.40" */
  Pitch: string
  /** ☆☆☆ ✔ 5776 */
  PitchAngle: number
  /** ☆☆☆ ✔ "10 s" */
  PlaybackMonitorOffTime: string
  /** ☆☆☆   "Body Battery" */
  PowerSource: string
  /** ☆☆☆ ✔ {"year":0,"month":0,"day":0,"hour":0,"minute":0,"second":0} */
  PowerUpTime: ExifDateTime
  /** ☆☆☆   0 */
  PreCaptureFrames: number
  /** ☆☆☆ ✔ "Preview" */
  PreviewButton: string
  /** ☆☆☆ ✔ "None" */
  PreviewButtonPlusDials: string
  /** ☆☆☆   "26 26 0 0" */
  PreviewImageBorders: string
  /** ☆☆☆   1024 */
  PreviewImageHeight: number
  /** ☆☆☆ ✔ 347190 */
  PreviewImageLength: number
  /** ☆☆☆   "1616x1080" */
  PreviewImageSize: string
  /** ☆☆☆ ✔ 1296968 */
  PreviewImageStart: number
  /** ☆☆☆ ✔ "No" */
  PreviewImageValid: string
  /** ☆☆☆   1536 */
  PreviewImageWidth: number
  /** ☆☆☆ ✔ 4 */
  PrimaryAFPoint: number
  /** ☆☆☆   2 */
  ProductionCode: number
  /** ☆☆☆   "Normal" */
  ProgramLine: string
  /** ☆☆☆ ✔ 0 */
  ProgramShift: number
  /** ★★☆ ✔ "Superfine" */
  Quality: string
  /** ☆☆☆ ✔ 0 */
  Rating: number
  /** ☆☆☆   "Little-endian (Intel, II)" */
  RawDataByteOrder: string
  /** ☆☆☆   "Swap" */
  RawDataCFAPattern: string
  /** ☆☆☆ ✔ "Off; 0; 0; 0" */
  RawDevArtFilter: string
  /** ☆☆☆ ✔ "Off" */
  RawDevAutoGradation: string
  /** ☆☆☆ ✔ "sRGB" */
  RawDevColorSpace: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevContrastValue: string
  /** ☆☆☆ ✔ "Edited (Landscape)" */
  RawDevEditStatus: string
  /** ☆☆☆ ✔ "Unknown (2)" */
  RawDevEngine: string
  /** ☆☆☆ ✔ 0 */
  RawDevExposureBiasValue: number
  /** ☆☆☆ ✔ 0 */
  RawDevGradation: number
  /** ☆☆☆ ✔ "0 0" */
  RawDevGrayPoint: string
  /** ☆☆☆ ✔ "" */
  RawDevMemoryColorEmphasis: string
  /** ☆☆☆ ✔ "(none)" */
  RawDevNoiseReduction: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevPMContrast: string
  /** ☆☆☆ ✔ "1 -2 -2 1" */
  RawDevPMNoiseFilter: string
  /** ☆☆☆ ✔ "Unknown (0)" */
  RawDevPMPictureTone: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevPMSaturation: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevPMSharpness: string
  /** ☆☆☆ ✔ "Unknown (0)" */
  RawDevPM_BWFilter: string
  /** ☆☆☆ ✔ "Natural" */
  RawDevPictureMode: string
  /** ☆☆☆ ✔ 0 */
  RawDevSaturation3: number
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevSaturationEmphasis: string
  /** ☆☆☆ ✔ "(none)" */
  RawDevSettings: string
  /** ☆☆☆ ✔ "0 -2 2" */
  RawDevSharpnessValue: string
  /** ☆☆☆ ✔ "0100" */
  RawDevVersion: string
  /** ☆☆☆ ✔ "0 0" */
  RawDevWBFineAdjustment: string
  /** ☆☆☆ ✔ "Unknown (3)" */
  RawDevWhiteBalance: string
  /** ☆☆☆ ✔ 0 */
  RawDevWhiteBalanceValue: number
  /** ☆☆☆   "6 (645D)" */
  RawDevelopmentProcess: string
  /** ☆☆☆ ✔ "Large" */
  RawJpgSize: string
  /** ☆☆☆ ✔ "40661 82449 82146 41069" */
  RawMeasuredRGGB: string
  /** ☆☆☆ ✔ "JPEG" */
  RecordMode: string
  /** ☆☆☆   2.28125 */
  RedBalance: number
  /** ☆☆☆ ✔ "No" */
  ReleaseButtonToUseDial: string
  /** ☆☆☆   2 */
  Resolution: number
  /** ☆☆☆   "HI" */
  ResolutionMode: string
  /** ☆☆☆ ✔ "inches" */
  ResolutionUnit: string
  /** ☆☆☆ ✔ "NEF Processing" */
  RetouchHistory: string
  /** ☆☆☆ ✔ "0200" */
  RetouchInfoVersion: string
  /** ☆☆☆ ✔ "On" */
  RetouchNEFProcessing: string
  /** ☆☆☆ ✔ "- 0 +" */
  ReverseIndicators: string
  /** ☆☆☆ ✔ 15095.9 */
  RollAngle: number
  /** ☆☆☆ ✔ 0 */
  Rotation: number
  /** ☆☆☆ ✔ 0 */
  RunTimeEpoch: number
  /** ☆☆☆ ✔ "Valid" */
  RunTimeFlags: string
  /** ☆☆☆ ✔ 1000000000 */
  RunTimeScale: number
  /** ☆☆☆ ✔ 98536337937083 */
  RunTimeValue: number
  /** ☆☆☆ ✔ "n/a" */
  SRAWQuality: string
  /** ☆☆☆   "40 mm" */
  SRFocalLength: string
  /** ☆☆☆   "0.00 s" */
  SRHalfPressTime: string
  /** ☆☆☆   "Not ready" */
  SRResult: string
  /** ☆☆☆   "Disable" */
  SafetyShift: string
  /** ☆☆☆ ✔ "Disable" */
  SafetyShiftInAvOrTv: string
  /** ☆☆☆   "Various Models (0x3000000)" */
  SamsungModelID: string
  /** ★☆☆ ✔ "Normal" */
  Saturation: string
  /** ☆☆☆ ✔ 0 */
  SaturationAuto: number
  /** ☆☆☆ ✔ 0 */
  SaturationFaithful: number
  /** ☆☆☆ ✔ 0 */
  SaturationLandscape: number
  /** ☆☆☆ ✔ 0 */
  SaturationNeutral: number
  /** ☆☆☆ ✔ 0 */
  SaturationPortrait: number
  /** ☆☆☆ ✔ 0 */
  SaturationStandard: number
  /** ☆☆☆ ✔ 0 */
  SaturationUserDef1: number
  /** ☆☆☆ ✔ 0 */
  SaturationUserDef2: number
  /** ☆☆☆ ✔ 0 */
  SaturationUserDef3: number
  /** ☆☆☆   "" */
  SceneAssist: string
  /** ☆☆☆ ✔ 0 */
  SceneDetect: number
  /** ☆☆☆ ✔ "Landscape" */
  SceneMode: string
  /** ☆☆☆   "Program" */
  SceneModeUsed: string
  /** ☆☆☆ ✔ "On" */
  ScreenTips: string
  /** ☆☆☆ ✔ "Unknown (0x1)" */
  SecondarySlotFunction: string
  /** ☆☆☆ ✔ "Off" */
  SelfTimer: string
  /** ☆☆☆ ✔ 0.1 */
  SelfTimer2: number
  /** ☆☆☆ ✔ 1 */
  SelfTimerShotCount: number
  /** ☆☆☆ ✔ "0.5 s" */
  SelfTimerShotInterval: string
  /** ☆☆☆ ✔ "10 s" */
  SelfTimerTime: string
  /** ☆☆☆   0 */
  SensitivityAdjust: number
  /** ☆☆☆ ✔ 0 */
  SensorBlueLevel: number
  /** ☆☆☆ ✔ 2322 */
  SensorBottomBorder: number
  /** ☆☆☆ ✔ "4010 290" */
  SensorCalibration: string
  /** ☆☆☆ ✔ 2328 */
  SensorHeight: number
  /** ☆☆☆ ✔ 52 */
  SensorLeftBorder: number
  /** ☆☆☆ ✔ "5.4 x 5.4 um" */
  SensorPixelSize: string
  /** ☆☆☆ ✔ 0 */
  SensorRedLevel: number
  /** ☆☆☆ ✔ 3507 */
  SensorRightBorder: number
  /** ☆☆☆   "24.024 x 16.038 mm" */
  SensorSize: string
  /** ☆☆☆ ✔ "48 48 0 C" */
  SensorTemperature: string
  /** ☆☆☆ ✔ 19 */
  SensorTopBorder: number
  /** ☆☆☆ ✔ 3516 */
  SensorWidth: number
  /** ★☆☆ ✔ 0 */
  SequenceNumber: number
  /** ☆☆☆ ✔ "0320131248" */
  SerialNumber: string
  /** ☆☆☆ ✔ "Format 2" */
  SerialNumberFormat: string
  /** ☆☆☆ ✔ "Normal" */
  SetButtonCrossKeysFunc: string
  /** ☆☆☆ ✔ "Default (no function)" */
  SetButtonWhenShooting: string
  /** ☆☆☆ ✔ "Off" */
  ShadingCompensation: string
  /** ☆☆☆ ✔ "Off" */
  ShadingCompensation2: string
  /** ☆☆☆   0 */
  Shadow: number
  /** ☆☆☆   "Off" */
  ShadowCorrection: string
  /** ☆☆☆ ✔ "Normal" */
  ShadowTone: string
  /** ☆☆☆   "On but Disabled" */
  ShakeReduction: string
  /** ★☆☆ ✔ "0" */
  Sharpness: string
  /** ☆☆☆ ✔ 3 */
  SharpnessAuto: number
  /** ☆☆☆   592 */
  SharpnessFactor: number
  /** ☆☆☆ ✔ 0 */
  SharpnessFaithful: number
  /** ☆☆☆ ✔ "n/a" */
  SharpnessFrequency: string
  /** ☆☆☆ ✔ 4 */
  SharpnessLandscape: number
  /** ☆☆☆ ✔ 3 */
  SharpnessMonochrome: number
  /** ☆☆☆ ✔ 0 */
  SharpnessNeutral: number
  /** ☆☆☆ ✔ 2 */
  SharpnessPortrait: number
  /** ☆☆☆ ✔ "0 (min -5, max 5)" */
  SharpnessSetting: string
  /** ☆☆☆ ✔ 3 */
  SharpnessStandard: number
  /** ☆☆☆ ✔ 3 */
  SharpnessUserDef1: number
  /** ☆☆☆ ✔ 3 */
  SharpnessUserDef2: number
  /** ☆☆☆ ✔ 3 */
  SharpnessUserDef3: number
  /** ☆☆☆ ✔ "Not Set" */
  ShootingInfoDisplay: string
  /** ☆☆☆ ✔ "10 s" */
  ShootingInfoMonitorOffTime: string
  /** ☆☆☆ ✔ "Single-Frame, Self-timer" */
  ShootingMode: string
  /** ☆☆☆ ✔ "0100" */
  ShotInfoVersion: string
  /** ☆☆☆ ✔ "AF/AE lock stop" */
  ShutterAELButton: string
  /** ☆☆☆ ✔ "Metering + AF start" */
  ShutterButtonAFOnButton: string
  /** ☆☆☆ ✔ 266 */
  ShutterCount: number
  /** ☆☆☆ ✔ "1st-curtain sync" */
  ShutterCurtainSync: string
  /** ☆☆☆   "Unknown (20)" */
  ShutterMode: string
  /** ☆☆☆ ✔ "No" */
  ShutterReleaseNoCFCard: string
  /** ☆☆☆ ✔ "Off" */
  ShutterSpeedLock: string
  /** ☆☆☆   "1/128" */
  ShutterSpeedValue: string
  /** ☆☆☆   "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" */
  SlaveFlashMeteringSegments: string
  /** ☆☆☆ ✔ "n/a" */
  SlowShutter: string
  /** ☆☆☆ ✔ "Off" */
  SlowSync: string
  /** ☆☆☆   "Blue; 38087" */
  SmartAlbumColor: string
  /** ☆☆☆ ✔ "Off" */
  SoftFocusFilter: string
  /** ☆☆☆   " " */
  Software: string
  /** ☆☆☆   0 */
  SourceDirectoryIndex: number
  /** ☆☆☆   0 */
  SourceFileIndex: number
  /** ☆☆☆ ✔ "Normal, Sequence: 0, Panorama: (none)" */
  SpecialMode: string
  /** ☆☆☆ ✔ 15120 */
  SpecularWhiteLevel: number
  /** ☆☆☆   "Center" */
  SpotMeteringMode: string
  /** ☆☆☆ ✔ "No" */
  StackedImage: string
  /** ☆☆☆ ✔ "6 s" */
  StandbyTimer: string
  /** ☆☆☆ ✔ "Off" */
  StoreByOrientation: string
  /** ☆☆☆ ✔ "Assist + AF" */
  SwitchToRegisteredAFPoint: string
  /** ☆☆☆ ✔ 2.8 */
  TargetAperture: number
  /** ☆☆☆ ✔ "1/60" */
  TargetExposureTime: string
  /** ☆☆☆   "n/a" */
  TextEncoding: string
  /** ☆☆☆   120 */
  ThumbnailHeight: number
  /** ☆☆☆ ✔ "0 0 0 0" */
  ThumbnailImageValidArea: string
  /** ☆☆☆   160 */
  ThumbnailWidth: number
  /** ☆☆☆   {"hour":6,"minute":22,"second":54} */
  Time: ExifTime
  /** ☆☆☆   "17:35:05.80" */
  TimeCreated: ExifTime
  /** ☆☆☆   "00:02:59.65" */
  TimeSincePowerOn: string
  /** ☆☆☆ ✔ "+00:00" */
  TimeZone: string
  /** ☆☆☆ ✔ "London" */
  TimeZoneCity: string
  /** ☆☆☆ ✔ "Normal" */
  ToneComp: string
  /** ☆☆☆ ✔ "Standard" */
  ToneCurve: string
  /** ☆☆☆ ✔ "Highlights; 0; -7; 7; Shadows; 0; -7; 7; 0; 0; 0; 0" */
  ToneLevel: string
  /** ☆☆☆ ✔ "None" */
  ToningEffect: string
  /** ☆☆☆ ✔ "n/a" */
  ToningEffectAuto: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectMonochrome: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectUserDef1: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectUserDef2: string
  /** ☆☆☆ ✔ "None" */
  ToningEffectUserDef3: string
  /** ☆☆☆ ✔ "n/a" */
  ToningSaturation: string
  /** ☆☆☆   1 */
  TotalZoom: number
  /** ☆☆☆ ✔ "Off" */
  ToyCameraFilter: string
  /** ☆☆☆   "n/a" */
  TravelDay: string
  /** ☆☆☆   "Subtle Correction" */
  TungstenAWB: string
  /** ☆☆☆ ✔ "Enable After AF" */
  USMLensElectronicMF: string
  /** ☆☆☆ ✔ "Standard" */
  UserDef1PictureStyle: string
  /** ☆☆☆ ✔ "Standard" */
  UserDef2PictureStyle: string
  /** ☆☆☆ ✔ "Standard" */
  UserDef3PictureStyle: string
  /** ☆☆☆   "Auto" */
  VFDisplayIllumination: string
  /** ☆☆☆ ✔ 0 */
  VRDOffset: number
  /** ☆☆☆ ✔ "0100" */
  VRInfoVersion: string
  /** ☆☆☆ ✔ "Normal" */
  VRMode: string
  /** ☆☆☆ ✔ 9 */
  ValidAFPoints: number
  /** ☆☆☆ ✔ "12 0" */
  ValidBits: string
  /** ☆☆☆ ✔ "" */
  VariProgram: string
  /** ☆☆☆ ✔ "0130" */
  Version: string
  /** ☆☆☆ ✔ "On" */
  VibrationReduction: string
  /** ☆☆☆ ✔ "Normal" */
  VignetteControl: string
  /** ☆☆☆ ✔ 0 */
  VignettingCorrVersion: number
  /** ☆☆☆   394 */
  WBBlueLevel: number
  /** ☆☆☆ ✔ "Off" */
  WBBracketMode: string
  /** ☆☆☆ ✔ 0 */
  WBBracketValueAB: number
  /** ☆☆☆ ✔ 0 */
  WBBracketValueGM: number
  /** ☆☆☆ ✔ "WB Bracketing Disabled" */
  WBBracketingSteps: string
  /** ☆☆☆   264 */
  WBGreenLevel: number
  /** ☆☆☆   "Auto" */
  WBMode: string
  /** ☆☆☆   569 */
  WBRedLevel: number
  /** ☆☆☆ ✔ 0 */
  WBShiftAB: number
  /** ☆☆☆ ✔ 0 */
  WBShiftGM: number
  /** ☆☆☆   0 */
  WB_GLevel: number
  /** ☆☆☆   "256 454 370 256" */
  WB_GRBGLevels: string
  /** ☆☆☆   "0 0 0 0" */
  WB_RBGGLevels: string
  /** ☆☆☆ ✔ "2.078125 1.29296875 1 1" */
  WB_RBLevels: string
  /** ☆☆☆ ✔ "290 692 256 256" */
  WB_RBLevels3000K: string
  /** ☆☆☆ ✔ "354 556 256 256" */
  WB_RBLevels3300K: string
  /** ☆☆☆ ✔ "382 514 256 256" */
  WB_RBLevels3600K: string
  /** ☆☆☆ ✔ "406 482 256 256" */
  WB_RBLevels3900K: string
  /** ☆☆☆ ✔ "486 550 256 256" */
  WB_RBLevels4000K: string
  /** ☆☆☆ ✔ "434 460 256 256" */
  WB_RBLevels4300K: string
  /** ☆☆☆ ✔ "480 468 256 256" */
  WB_RBLevels4500K: string
  /** ☆☆☆ ✔ "470 426 256 256" */
  WB_RBLevels4800K: string
  /** ☆☆☆ ✔ "500 398 256 256" */
  WB_RBLevels5300K: string
  /** ☆☆☆ ✔ "540 364 256 256" */
  WB_RBLevels6000K: string
  /** ☆☆☆ ✔ "572 390 256 256" */
  WB_RBLevels6600K: string
  /** ☆☆☆ ✔ "586 316 256 256" */
  WB_RBLevels7500K: string
  /** ☆☆☆ ✔ "468 414 256 256" */
  WB_RBLevelsCWB1: string
  /** ☆☆☆ ✔ "384 384 256 256" */
  WB_RBLevelsCWB2: string
  /** ☆☆☆ ✔ "384 384 256 256" */
  WB_RBLevelsCWB3: string
  /** ☆☆☆ ✔ "384 384 256 256" */
  WB_RBLevelsCWB4: string
  /** ☆☆☆ ✔ "286 256 256 479" */
  WB_RGGBLevels: string
  /** ☆☆☆ ✔ "2338 1019 1019 1587" */
  WB_RGGBLevelsAsShot: string
  /** ☆☆☆ ✔ "2338 1023 1023 1587" */
  WB_RGGBLevelsAuto: string
  /** ☆☆☆ ✔ "2639 1023 1023 1353" */
  WB_RGGBLevelsCloudy: string
  /** ☆☆☆ ✔ "128 128 128 128" */
  WB_RGGBLevelsCustom: string
  /** ☆☆☆ ✔ "2425 1023 1023 1492" */
  WB_RGGBLevelsDaylight: string
  /** ☆☆☆ ✔ "2735 1023 1023 1306" */
  WB_RGGBLevelsFlash: string
  /** ☆☆☆ ✔ "2038 1023 1023 1969" */
  WB_RGGBLevelsFluorescent: string
  /** ☆☆☆   "14665 8192 8192 8981" */
  WB_RGGBLevelsFluorescentD: string
  /** ☆☆☆   "12258 8192 8192 10114" */
  WB_RGGBLevelsFluorescentN: string
  /** ☆☆☆   "10943 8192 8192 12318" */
  WB_RGGBLevelsFluorescentW: string
  /** ☆☆☆ ✔ "2185 1024 1024 1535" */
  WB_RGGBLevelsKelvin: string
  /** ☆☆☆ ✔ "1912 1028 1019 1791" */
  WB_RGGBLevelsMeasured: string
  /** ☆☆☆ ✔ "8191 1024 1024 8191" */
  WB_RGGBLevelsPC1: string
  /** ☆☆☆ ✔ "8191 1024 1024 8191" */
  WB_RGGBLevelsPC2: string
  /** ☆☆☆ ✔ "8191 1024 1024 8191" */
  WB_RGGBLevelsPC3: string
  /** ☆☆☆ ✔ "2847 1023 1023 1249" */
  WB_RGGBLevelsShade: string
  /** ☆☆☆ ✔ "1597 1023 1023 2302" */
  WB_RGGBLevelsTungsten: string
  /** ☆☆☆ ✔ "Off" */
  WatercolorFilter: string
  /** ★☆☆ ✔ "Auto" */
  WhiteBalance: string
  /** ☆☆☆ ✔ "Auto (Keep Warm Color Off)" */
  WhiteBalance2: string
  /** ☆☆☆   "Off" */
  WhiteBalanceAutoAdjustment: string
  /** ☆☆☆   0 */
  WhiteBalanceBias: number
  /** ☆☆☆ ✔ 0 */
  WhiteBalanceBlue: number
  /** ☆☆☆ ✔ "0 0" */
  WhiteBalanceBracket: string
  /** ☆☆☆ ✔ "Red +0, Blue +0" */
  WhiteBalanceFineTune: string
  /** ☆☆☆   "Unknown (0)" */
  WhiteBalanceMode: string
  /** ☆☆☆ ✔ 0 */
  WhiteBalanceRed: number
  /** ☆☆☆   "Auto" */
  WhiteBalanceSet: string
  /** ☆☆☆ ✔ "Auto" */
  WhiteBalanceTemperature: string
  /** ☆☆☆   0 */
  WhiteBoard: number
  /** ☆☆☆   "10560 8192 8192 9888" */
  WhitePoint: string
  /** ☆☆☆   "Home" */
  WorldTimeLocation: string
  /** ☆☆☆   0 */
  X3FillLight: number
  /** ☆☆☆ ✔ 300 */
  XResolution: number
  /** ☆☆☆ ✔ "Co-sited" */
  YCbCrPositioning: string
  /** ☆☆☆ ✔ 300 */
  YResolution: number
  /** ☆☆☆ ✔ 24599.7 */
  YawAngle: number
  /** ☆☆☆   2005 */
  YearCreated: number
  /** ☆☆☆ ✔ 2584 */
  ZoomSourceWidth: number
  /** ☆☆☆ ✔ 31 */
  ZoomStepCount: number
  /** ☆☆☆ ✔ 2584 */
  ZoomTargetWidth: number
}

export interface JFIFTags {
  /** ☆☆☆ ✔ 1.01 */
  JFIFVersion: number
  /** ☆☆☆ ✔ "inches" */
  ResolutionUnit: string
  /** ☆☆☆ ✔ 72 */
  XResolution: number
  /** ☆☆☆ ✔ 72 */
  YResolution: number
}

export interface XMPTags {
  /** ☆☆☆ ✔ "uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b" */
  About: string
  /** ☆☆☆   true */
  AlreadyApplied: boolean
  /** ☆☆☆ ✔ {"year":2015,"month":11,"day":11,"hour":11,"minute":27,"second":49} */
  CreateDate: ExifDateTime
  /** ☆☆☆ ✔ "Photos 1.0.1" */
  CreatorTool: string
  /** ☆☆☆ ✔ {"year":2015,"month":11,"day":11,"hour":11,"minute":27,"second":49} */
  DateCreated: ExifDate
  /** ☆☆☆   "2010:12:19 15:23:21.00+09:00" */
  DateTimeDigitized: string
  /** ☆☆☆   "2010:12:19 15:23:21.00+09:00" */
  DateTimeOriginal: ExifDateTime
  /** ☆☆☆ ✔ "Castle Rock" */
  Description: string
  /** ☆☆☆ ✔ "D2A319020F9FD0935CABCB60F534E0E0" */
  DocumentID: string
  /** ☆☆☆   3456 */
  ExifImageHeight: number
  /** ☆☆☆   5184 */
  ExifImageWidth: number
  /** ☆☆☆   "0230" */
  ExifVersion: string
  /** ☆☆☆   0 */
  ExposureCompensation: number
  /** ☆☆☆ ✔ 0 */
  FlashCompensation: number
  /** ☆☆☆   false */
  FlashFired: boolean
  /** ☆☆☆   false */
  FlashFunction: boolean
  /** ☆☆☆   "Off" */
  FlashMode: string
  /** ☆☆☆   false */
  FlashRedEyeMode: boolean
  /** ☆☆☆   "No return detection" */
  FlashReturn: string
  /** ☆☆☆ ✔ "image/jpeg" */
  Format: string
  /** ☆☆☆ ✔ ["saved","saved"] */
  HistoryAction: string[]
  /** ☆☆☆ ✔ ["/metadata","/metadata"] */
  HistoryChanged: string[]
  /** ☆☆☆ ✔ ["xmp.iid:4d4cb5c0-5d51-4cc0-a638-bc5a6cf3f44f","xmp.iid:195a0cd4-8115-4cb9-89e… */
  HistoryInstanceID: string[]
  /** ☆☆☆ ✔ ["Adobe Photoshop Camera Raw 8.6","Adobe Photoshop Camera Raw 8.6 (Macintosh)"] */
  HistorySoftwareAgent: string[]
  /** ☆☆☆ ✔ ["2014:11:11 15:27:28Z","2014:11:11 15:27:29Z"] */
  HistoryWhen: string[]
  /** ☆☆☆ ✔ 1425 */
  ImageNumber: number
  /** ☆☆☆ ✔ "xmp.iid:195a0cd4-8115-4cb9-89e4-fe6d8b9319fd" */
  InstanceID: string
  /** ☆☆☆   "選択" */
  Label: string
  /** ☆☆☆ ✔ "iPhone 6 Plus back camera 4.15mm f/2.2" */
  Lens: string
  /** ☆☆☆ ✔ "4.15mm f/2.2" */
  LensInfo: string
  /** ☆☆☆ ✔ "iPhone 6 Plus back camera 4.15mm f/2.2" */
  LensModel: string
  /** ☆☆☆ ✔ "00002042bc" */
  LensSerialNumber: string
  /** ☆☆☆   "Canon" */
  Make: string
  /** ☆☆☆ ✔ {"year":2014,"month":11,"day":11,"hour":15,"minute":27,"second":29,"tzoffsetMin… */
  MetadataDate: ExifDateTime
  /** ☆☆☆   "Canon EOS Kiss X5" */
  Model: string
  /** ☆☆☆ ✔ {"year":2015,"month":11,"day":11,"hour":11,"minute":27,"second":49} */
  ModifyDate: ExifDateTime
  /** ☆☆☆ ✔ "D2A319020F9FD0935CABCB60F534E0E0" */
  OriginalDocumentID: string
  /** ☆☆☆ ✔ 32 */
  PhotographicSensitivity: number
  /** ☆☆☆ ✔ 2 */
  Rating: number
  /** ☆☆☆   0 */
  RatingPercent: number
  /** ☆☆☆ ✔ "DSCF0722.JPG" */
  RawFileName: string
  /** ☆☆☆ ✔ 960 */
  RegionAppliedToDimensionsH: number
  /** ☆☆☆ ✔ "pixel" */
  RegionAppliedToDimensionsUnit: string
  /** ☆☆☆ ✔ 1280 */
  RegionAppliedToDimensionsW: number
  /** ☆☆☆ ✔ 0.391667 */
  RegionAreaH: number
  /** ☆☆☆ ✔ "normalized" */
  RegionAreaUnit: string
  /** ☆☆☆ ✔ 0.29375 */
  RegionAreaW: number
  /** ☆☆☆ ✔ 0.46875 */
  RegionAreaX: number
  /** ☆☆☆ ✔ 0.670833 */
  RegionAreaY: number
  /** ☆☆☆ ✔ 270 */
  RegionExtensionsAngleInfoRoll: number
  /** ☆☆☆ ✔ 0 */
  RegionExtensionsAngleInfoYaw: number
  /** ☆☆☆ ✔ 306 */
  RegionExtensionsConfidenceLevel: number
  /** ☆☆☆ ✔ 1 */
  RegionExtensionsFaceID: number
  /** ☆☆☆ ✔ 925958091 */
  RegionExtensionsTimeStamp: number
  /** ☆☆☆ ✔ "Face" */
  RegionType: string
  /** ☆☆☆   "inches" */
  ResolutionUnit: string
  /** ☆☆☆ ✔ "000019900153" */
  SerialNumber: string
  /** ☆☆☆   "Auto" */
  WhiteBalance: string
  /** ☆☆☆ ✔ "XMP Core 5.4.0" */
  XMPToolkit: string
  /** ☆☆☆   72 */
  XResolution: number
  /** ☆☆☆   72 */
  YResolution: number
}

export interface PhotoshopTags {
  /** ☆☆☆ ✔ "d41d8cd98f00b204e9800998ecf8427e" */
  IPTCDigest: string
}

export interface ICC_ProfileTags {
  /** ☆☆☆ ✔ "0.14307 0.06061 0.7141" */
  BlueMatrixColumn: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  BlueTRC: string
  /** ☆☆☆ ✔ "Not Embedded, Independent" */
  CMMFlags: string
  /** ☆☆☆ ✔ "1.04788 0.02292 -0.0502 0.02959 0.99048 -0.01706 -0.00923 0.01508 0.75168" */
  ChromaticAdaptation: string
  /** ☆☆☆ ✔ "RGB " */
  ColorSpaceData: string
  /** ☆☆☆ ✔ "0.9642 1 0.82491" */
  ConnectionSpaceIlluminant: string
  /** ☆☆☆ ✔ "Reflective, Glossy, Positive, Color" */
  DeviceAttributes: string
  /** ☆☆☆ ✔ "IEC " */
  DeviceManufacturer: string
  /** ☆☆☆ ✔ "IEC http://www.iec.ch" */
  DeviceMfgDesc: string
  /** ☆☆☆ ✔ "sRGB" */
  DeviceModel: string
  /** ☆☆☆ ✔ "IEC 61966-2.1 Default RGB colour space - sRGB" */
  DeviceModelDesc: string
  /** ☆☆☆ ✔ "0.38515 0.71687 0.09708" */
  GreenMatrixColumn: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  GreenTRC: string
  /** ☆☆☆ ✔ "76.03647 80 87.12462" */
  Luminance: string
  /** ☆☆☆ ✔ "0 0 0" */
  MeasurementBacking: string
  /** ☆☆☆ ✔ "0.999%" */
  MeasurementFlare: string
  /** ☆☆☆ ✔ "Unknown" */
  MeasurementGeometry: string
  /** ☆☆☆ ✔ "D65" */
  MeasurementIlluminant: string
  /** ☆☆☆ ✔ "CIE 1931" */
  MeasurementObserver: string
  /** ☆☆☆ ✔ "0 0 0" */
  MediaBlackPoint: string
  /** ☆☆☆ ✔ "0.95045 1 1.08905" */
  MediaWhitePoint: string
  /** ☆☆☆ ✔ "Microsoft Corporation" */
  PrimaryPlatform: string
  /** ☆☆☆ ✔ "Lino" */
  ProfileCMMType: string
  /** ☆☆☆ ✔ "Display Device Profile" */
  ProfileClass: string
  /** ☆☆☆ ✔ "XYZ " */
  ProfileConnectionSpace: string
  /** ☆☆☆ ✔ "Copyright (c) 1998 Hewlett-Packard Company" */
  ProfileCopyright: string
  /** ☆☆☆ ✔ "HP  " */
  ProfileCreator: string
  /** ☆☆☆ ✔ {"year":1998,"month":2,"day":9,"hour":6,"minute":49,"second":0} */
  ProfileDateTime: ExifDateTime
  /** ☆☆☆ ✔ "sRGB IEC61966-2.1" */
  ProfileDescription: string
  /** ☆☆☆ ✔ "acsp" */
  ProfileFileSignature: string
  /** ☆☆☆ ✔ 0 */
  ProfileID: number
  /** ☆☆☆ ✔ "2.1.0" */
  ProfileVersion: string
  /** ☆☆☆ ✔ "0.43607 0.22249 0.01392" */
  RedMatrixColumn: string
  /** ☆☆☆ ✔ "(Binary data 2060 bytes, use -b option to extract)" */
  RedTRC: string
  /** ☆☆☆ ✔ "Perceptual" */
  RenderingIntent: string
  /** ☆☆☆ ✔ "Cathode Ray Tube Display" */
  Technology: string
  /** ☆☆☆ ✔ "Reference Viewing Condition in IEC61966-2.1" */
  ViewingCondDesc: string
  /** ☆☆☆ ✔ "19.6445 20.3718 16.8089" */
  ViewingCondIlluminant: string
  /** ☆☆☆ ✔ "D50" */
  ViewingCondIlluminantType: string
  /** ☆☆☆ ✔ "3.92889 4.07439 3.36179" */
  ViewingCondSurround: string
}

export interface IPTCTags {
  /** ☆☆☆ ✔ 4 */
  ApplicationRecordVersion: number
  /** ☆☆☆ ✔ "UTF8" */
  CodedCharacterSet: string
  /** ☆☆☆ ✔ {"year":2014,"month":10,"day":31} */
  DateCreated: ExifDate
  /** ☆☆☆ ✔ {"year":2016,"month":8,"day":12} */
  DigitalCreationDate: ExifDate
  /** ☆☆☆ ✔ {"hour":13,"minute":28,"second":50} */
  DigitalCreationTime: ExifTime
  /** ☆☆☆ ✔ {"hour":13,"minute":15,"second":35} */
  TimeCreated: ExifTime
}

export interface MPFTags {
  /** ☆☆☆ ✔ 0 */
  DependentImage1EntryNumber: number
  /** ☆☆☆ ✔ 0 */
  DependentImage2EntryNumber: number
  /** ☆☆☆   "(Binary data 66 bytes, use -b option to extract)" */
  ImageUIDList: string
  /** ☆☆☆ ✔ "0100" */
  MPFVersion: string
  /** ☆☆☆ ✔ "Dependent child image" */
  MPImageFlags: string
  /** ☆☆☆ ✔ "JPEG" */
  MPImageFormat: string
  /** ☆☆☆ ✔ 681513 */
  MPImageLength: number
  /** ☆☆☆ ✔ 7732736 */
  MPImageStart: number
  /** ☆☆☆ ✔ "Large Thumbnail (full HD equivalent)" */
  MPImageType: string
  /** ☆☆☆ ✔ 2 */
  NumberOfImages: number
  /** ☆☆☆   1 */
  TotalFrames: number
}

export interface PrintIMTags {
  /** ☆☆☆ ✔ "0250" */
  PrintIMVersion: string
}

export interface FlashPixTags {
  /** ☆☆☆   "Unicode UTF-16, little endian" */
  CodePage: string
  /** ☆☆☆   "Picoss" */
  CreatingApplication: string
  /** ☆☆☆   "10000230-6FC0-11D0-BD01-00609719A180" */
  ExtensionClassID: string
  /** ☆☆☆   {"year":2003,"month":3,"day":29,"hour":17,"minute":47,"second":50} */
  ExtensionCreateDate: ExifDateTime
  /** ☆☆☆   "Presized image for LCD display" */
  ExtensionDescription: string
  /** ☆☆☆   {"year":2003,"month":3,"day":29,"hour":17,"minute":47,"second":50} */
  ExtensionModifyDate: ExifDateTime
  /** ☆☆☆   "Screen nail" */
  ExtensionName: string
  /** ☆☆☆   "Invalidated By Modification" */
  ExtensionPersistence: string
  /** ☆☆☆ ✔ "(Binary data 59568 bytes, use -b option to extract)" */
  PreviewImage: string
  /** ☆☆☆ ✔ 480 */
  PreviewImageHeight: number
  /** ☆☆☆ ✔ 640 */
  PreviewImageWidth: number
  /** ☆☆☆   "(Binary data 59606 bytes, use -b option to extract)" */
  ScreenNail: string
  /** ☆☆☆   1 */
  UsedExtensionNumbers: number
}

export interface MetaTags {
  /** ☆☆☆   "0110\u0000" */
  MetadataNumber: string
}

export interface APP4Tags {
  /** ☆☆☆   776 */
  PreviewImageHeight: number
  /** ☆☆☆   1296 */
  PreviewImageWidth: number
  /** ☆☆☆   85 */
  PreviewQuality: number
}

export interface Tags extends
  ExifToolTags,
  FileTags,
  EXIFTags,
  CompositeTags,
  MakerNotesTags,
  JFIFTags,
  XMPTags,
  PhotoshopTags,
  ICC_ProfileTags,
  IPTCTags,
  MPFTags,
  PrintIMTags,
  FlashPixTags,
  MetaTags,
  APP4Tags {
  errors: string[]
  SourceFile: string
}

