/* tslint:disable:class-name */
import { ExifDate, ExifTime, ExifDateTime } from './datetime'

// Autogenerated by "npm run mktags" on Thu Oct 20 2016.

// Comments by each tag include likelihood (★★★ is > 70%, ☆☆☆ is rare)
// An example value, JSON stringified, follows the likelihood rating.

export interface ExifToolTags {
  ExifToolVersion: number // ★★★ 10.3
  Warning: string // ☆☆☆ "[minor] Unrecognized MakerNotes"
}

export interface FileTags {
  BitsPerSample: number[] // ★★★ 8
  ColorComponents: number // ★★★ 3
  Comment: string // ☆☆☆ "AppleMark\n"
  CurrentIPTCDigest: string // ☆☆☆ "d41d8cd98f00b204e9800998ecf8427e"
  Directory: string // ★★★ "C:/Users/mrm/Desktop/test/Apple"
  EncodingProcess: string // ★★★ "Baseline DCT, Huffman coding"
  ExifByteOrder: string // ★★★ "Big-endian (Motorola, MM)"
  FileAccessDate: ExifDateTime // ★★★ {"year":2016,"month":10,"day":18,"hour":20,"minute":12,"second":15}
  FileCreateDate: ExifDateTime // ★★★ {"year":2016,"month":10,"day":18,"hour":20,"minute":12,"second":15}
  FileModifyDate: ExifDateTime // ★★★ {"year":2013,"month":1,"day":23,"hour":6,"minute":30,"second":4}
  FileName: string // ★★★ "Apple_iPad_mini.jpg"
  FilePermissions: string // ★★★ "rw-rw-rw-"
  FileSize: string // ★★★ "12 kB"
  FileType: string // ★★★ "JPEG"
  FileTypeExtension: string // ★★★ "jpg"
  ImageHeight: number // ★★★ 8
  ImageWidth: number // ★★★ 8
  MIMEType: string // ★★★ "image/jpeg"
  PreviewImage: string // ☆☆☆ "(Binary data 133551 bytes, use -b option to extract)"
  YCbCrSubSampling: string // ★★★ "YCbCr4:2:0 (2 2)"
}

export interface EXIFTags {
  ApertureValue: number // ★☆☆ 2.4
  Artist: string // ☆☆☆ ""
  BitsPerSample: number[] // ☆☆☆ "8 8 8"
  BrightnessValue: number // ☆☆☆ 8.717925387
  CFAPattern: string // ☆☆☆ "[Red,Green][Green,Blue]"
  ColorSpace: string // ★★★ "sRGB"
  ComponentsConfiguration: string // ★★★ "Y, Cb, Cr, -"
  CompressedBitsPerPixel: number // ★☆☆ 2
  Compression: string // ★★★ "JPEG (old-style)"
  Contrast: string // ★☆☆ "Normal"
  Copyright: string // ☆☆☆ ""
  CreateDate: ExifDateTime // ★★★ {"year":2012,"month":11,"day":10,"hour":10,"minute":46,"second":58}
  CustomRendered: string // ★★☆ "Unknown (2)"
  DateTimeOriginal: ExifDateTime // ★★★ {"year":2012,"month":11,"day":10,"hour":10,"minute":46,"second":58}
  DeviceSettingDescription: string // ☆☆☆ "(Binary data 4 bytes, use -b option to extract)"
  DigitalZoomRatio: number // ★★☆ 1.042758621
  ExifImageHeight: number // ★★★ 1936
  ExifImageWidth: number // ★★★ 2592
  ExifVersion: string // ★★★ "0221"
  ExposureCompensation: number // ★★☆ 0
  ExposureIndex: number // ☆☆☆ 200
  ExposureMode: string // ★★☆ "Auto"
  ExposureProgram: string // ★★☆ "Program AE"
  ExposureTime: string // ★★★ "1/604"
  FNumber: number // ★★★ 2.4
  FileSource: string // ★★☆ "Reflection Print Scanner"
  Flash: string // ★★★ "No flash function"
  FlashpixVersion: string // ★★★ "0100"
  FocalLength: string // ★★★ "3.3 mm"
  FocalLengthIn35mmFormat: string // ★☆☆ "33 mm"
  FocalPlaneResolutionUnit: string // ★☆☆ "inches"
  FocalPlaneXResolution: number // ★☆☆ 12401.91388
  FocalPlaneYResolution: number // ★☆☆ 12461.53846
  GPSAltitude: string // ☆☆☆ "54 m"
  GPSAltitudeRef: string // ☆☆☆ "Above Sea Level"
  GPSDateStamp: ExifDate // ☆☆☆ {"tzoffset":0,"year":2015,"month":9,"day":5}
  GPSImgDirection: number // ☆☆☆ 94.8004158
  GPSImgDirectionRef: string // ☆☆☆ "True North"
  GPSLatitude: number // ☆☆☆ 40.86041667
  GPSLatitudeRef: string // ☆☆☆ "North"
  GPSLongitude: number // ☆☆☆ 25.83040556
  GPSLongitudeRef: string // ☆☆☆ "East"
  GPSMapDatum: string // ☆☆☆ "WGS-84"
  GPSProcessingMethod: string // ☆☆☆ "GPS"
  GPSSatellites: string // ☆☆☆ ""
  GPSStatus: string // ☆☆☆ "Measurement Active"
  GPSTimeStamp: ExifTime // ☆☆☆ {"tzoffset":0,"hour":16,"minute":27,"second":22}
  GPSVersionID: string // ☆☆☆ "2.2.0.0"
  GainControl: string // ☆☆☆ "Unknown (256)"
  Gamma: number // ☆☆☆ 2.2
  ISO: number // ★★☆ 32
  ImageDescription: string // ★☆☆ "Back Camera"
  ImageHeight: number // ☆☆☆ 60
  ImageUniqueID: string // ☆☆☆ "b6cbe2dd40d4d9de189b18448524a417"
  ImageWidth: number // ☆☆☆ 80
  InteropIndex: string // ★★★ "R98 - DCF basic file (sRGB)"
  InteropVersion: string // ★★★ "0100"
  LensInfo: string // ☆☆☆ "3.3mm f/2.4"
  LensMake: string // ☆☆☆ "Apple"
  LensModel: string // ☆☆☆ "iPad mini 2 back camera 3.3mm f/2.4"
  LensSerialNumber: string // ☆☆☆ "00002042bc"
  LightSource: string // ★☆☆ "Daylight"
  Make: string // ★★★ "Apple"
  MakerNoteUnknownText: string // ☆☆☆ "(Binary data 460 bytes, use -b option to extract)"
  MaxApertureValue: number // ★★☆ 2.8
  MeteringMode: string // ★★★ "Spot"
  Model: string // ★★★ "iPad mini"
  ModifyDate: ExifDateTime // ★★★ {"year":2012,"month":11,"day":10,"hour":10,"minute":46,"second":58}
  OffsetSchema: number // ☆☆☆ -230
  Orientation: string // ★★★ "Horizontal (normal)"
  OwnerName: string // ☆☆☆ ""
  Padding: string // ☆☆☆ "(Binary data 2060 bytes, use -b option to extract)"
  PhotometricInterpretation: string // ☆☆☆ "YCbCr"
  PrimaryChromaticities: string // ☆☆☆ "0.64 0.33 0.3 0.6 0.15 0.06"
  RecommendedExposureIndex: number // ☆☆☆ 1600
  RelatedImageHeight: number // ☆☆☆ 1944
  RelatedImageWidth: number // ☆☆☆ 2592
  RelatedSoundFile: string // ☆☆☆ "            "
  ResolutionUnit: string // ★★★ "inches"
  RowsPerStrip: number // ☆☆☆ 60
  SamplesPerPixel: number // ☆☆☆ 3
  Saturation: string // ★☆☆ "Normal"
  SceneCaptureType: string // ★★☆ "Standard"
  SceneType: string // ★☆☆ "Directly photographed"
  SensingMethod: string // ★☆☆ "One-chip color area"
  SensitivityType: string // ☆☆☆ "Recommended Exposure Index"
  SerialNumber: string // ☆☆☆ "000019900153"
  Sharpness: string // ★☆☆ "Normal"
  ShutterSpeedValue: string // ★☆☆ "1/604"
  Software: string // ★★☆ "6.0.1"
  StripByteCounts: number // ☆☆☆ 9600
  StripOffsets: number // ☆☆☆ 796
  SubSecTime: number // ☆☆☆ 234
  SubSecTimeDigitized: number // ☆☆☆ 718
  SubSecTimeOriginal: number // ☆☆☆ 718
  SubjectArea: string // ☆☆☆ "1836 859 484 484"
  SubjectDistance: string // ☆☆☆ "0.488 m"
  SubjectDistanceRange: string // ☆☆☆ "Unknown"
  ThumbnailLength: number // ★★★ 9462
  ThumbnailOffset: number // ★★★ 688
  UserComment: string // ★★☆ ""
  WhiteBalance: string // ★★★ "Auto"
  WhitePoint: string // ☆☆☆ "0.3127 0.329"
  XResolution: number // ★★★ 72
  YCbCrCoefficients: string // ☆☆☆ "0.299 0.587 0.114"
  YCbCrPositioning: string // ★★★ "Centered"
  YResolution: number // ★★★ 72
}

export interface CompositeTags {
  Aperture: number // ★★★ 2.4
  AutoFocus: string // ☆☆☆ "On"
  BlueBalance: number // ☆☆☆ 1.557409
  CircleOfConfusion: string // ★★☆ "0.003 mm"
  ConditionalFEC: number // ☆☆☆ 0
  DOF: string // ★☆☆ "inf (2.13 m - inf)"
  DateTimeCreated: ExifDateTime // ☆☆☆ {"year":2014,"month":10,"day":31,"hour":13,"minute":15,"second":35}
  DriveMode: string // ☆☆☆ "Continuous Shooting"
  ExtenderStatus: string // ☆☆☆ "Not attached"
  FOV: string // ★★☆ "57.2 deg"
  FileNumber: string // ☆☆☆ "100-0285"
  Flash: string // ☆☆☆ "Off, Did not fire"
  FlashType: string // ☆☆☆ "Built-In Flash"
  FocalLength35efl: string // ★★★ "3.3 mm (35 mm equivalent: 33.0 mm)"
  GPSAltitude: string // ☆☆☆ "54 m Above Sea Level"
  GPSDateTime: ExifDateTime // ☆☆☆ {"year":2015,"month":9,"day":5,"hour":16,"minute":27,"second":22,"tzoffsetMinut…
  GPSLatitude: number // ☆☆☆ 40.86041667
  GPSLongitude: number // ☆☆☆ 25.83040556
  GPSPosition: string // ☆☆☆ "40.86041667 N, 25.83040556 E"
  HyperfocalDistance: string // ★★☆ "1.51 m"
  ISO: number // ☆☆☆ 141
  ImageSize: string // ★★★ "8x8"
  Lens: string // ☆☆☆ "6.1 - 61.0 mm"
  Lens35efl: string // ☆☆☆ "6.1 - 61.0 mm (35 mm equivalent: 39.8 - 398.4 mm)"
  LensID: string // ★☆☆ "Unknown 6-61mm"
  LensSpec: string // ☆☆☆ "11-27.5mm f/3.5-5.6 [4]"
  LightValue: number // ★★☆ 13.4
  Megapixels: number // ★★★ 0.000064
  PreviewImage: string // ★☆☆ "(Binary data 347190 bytes, use -b option to extract)"
  RedBalance: number // ☆☆☆ 2.294406
  RedEyeReduction: string // ☆☆☆ "Off"
  RunTimeSincePowerUp: string // ☆☆☆ "1 days 3:22:16"
  ScaleFactor35efl: number // ★★☆ 10
  ShootingMode: string // ☆☆☆ "Program AE"
  ShutterCurtainHack: string // ☆☆☆ "1st-curtain sync"
  ShutterSpeed: string // ★★★ "1/604"
  SubSecCreateDate: ExifDateTime // ☆☆☆ {"year":2015,"month":2,"day":14,"hour":16,"minute":36,"second":19}
  SubSecDateTimeOriginal: ExifDateTime // ☆☆☆ {"year":2015,"month":2,"day":14,"hour":16,"minute":36,"second":19}
  SubSecModifyDate: ExifDateTime // ☆☆☆ {"year":2008,"month":4,"day":23,"hour":14,"minute":28,"second":17}
  ThumbnailImage: string // ★★★ "(Binary data 9462 bytes, use -b option to extract)"
  WB_RGGBLevels: string // ☆☆☆ "2338 1019 1019 1587"
}

export interface MakerNotesTags {
  AEBAutoCancel: string // ☆☆☆ "On"
  AEBBracketValue: string // ☆☆☆ "+0.25"
  AEBSequence: string // ☆☆☆ "0,-,+"
  AEBSequenceAutoCancel: string // ☆☆☆ "0,-,+/Enabled"
  AEBShotCount: string // ☆☆☆ "3 shots"
  AELock: string // ☆☆☆ "Off"
  AELockButton: string // ☆☆☆ "AE/AF Lock"
  AESetting: string // ☆☆☆ "Normal AE"
  AFAperture: number // ☆☆☆ 3.1
  AFAreaHeight: number // ☆☆☆ 42
  AFAreaHeights: string // ☆☆☆ "37 37 37 37 37 37 37 37 37"
  AFAreaMode: string // ★☆☆ "Auto"
  AFAreaWidth: number // ☆☆☆ 369
  AFAreaWidths: string // ☆☆☆ "53 53 53 53 53 53 53 53 53"
  AFAreaXPositions: string // ☆☆☆ "-54 0 53 -54 0 53 -54 0 53"
  AFAreaYPositions: string // ☆☆☆ "-38 -38 -38 0 0 0 38 38 38"
  AFAreas: string // ☆☆☆ "none"
  AFAssist: string // ☆☆☆ "Emits/Fires"
  AFAssistBeam: string // ☆☆☆ "Emits"
  AFFineTune: string // ☆☆☆ "Off"
  AFFineTuneAdj: number // ☆☆☆ 0
  AFFineTuneIndex: string // ☆☆☆ "n/a"
  AFImageHeight: number // ☆☆☆ 240
  AFImageWidth: number // ☆☆☆ 320
  AFInfo2Version: string // ☆☆☆ "0200"
  AFMicroAdjMode: string // ☆☆☆ "Disable"
  AFMicroAdjValue: number // ☆☆☆ 0
  AFPoint: string // ★☆☆ "Auto AF point selection"
  AFPointDisplayDuringFocus: string // ☆☆☆ "Selected (constant)"
  AFPointIllumination: string // ☆☆☆ "On"
  AFPointSelected: string // ☆☆☆ "n/a"
  AFPointSelection: string // ☆☆☆ "H=AF+Main/V=AF+Command"
  AFPointsInFocus: number // ★☆☆ 4
  AFPointsSelected: string // ☆☆☆ "0,1,2,3,4,5,6"
  AFPointsUsed: string // ☆☆☆ "A8,A10,B4,B6,B8,B10,B12,C4,C6,C8,C12,D4,D6,D8,D10,D12,E4,E6,E8,E10,E12,F4,F6,F…
  AFResponse: string // ☆☆☆ "Standard"
  AFResult: number // ☆☆☆ 0
  AFSearch: string // ☆☆☆ "Not Ready"
  AIServoTrackingSensitivity: string // ☆☆☆ "Standard"
  AccelerationVector: string // ☆☆☆ "-1.008544087 -0.008590849015 -0.1717849637"
  AddAspectRatioInfo: string // ☆☆☆ "Off"
  AddOriginalDecisionData: string // ☆☆☆ "Off"
  AmbienceSelection: string // ☆☆☆ "Standard"
  ApertureValue: number // ☆☆☆ 8.6
  ArtFilter: string // ☆☆☆ "Off; 0; 0; 0"
  ArtFilterEffect: string // ☆☆☆ "Off; 0; 0; Partial Color 0; No Effect; 0; No Color Filter; 0; 0; 0; 0; 0; 0; 0…
  AspectFrame: string // ☆☆☆ "0 0 3967 2975"
  AspectRatio: string // ☆☆☆ "3:2"
  AutoBracketOrder: string // ☆☆☆ "0,-,+"
  AutoBracketSet: string // ☆☆☆ "AE & Flash"
  AutoDistortionControl: string // ☆☆☆ "Off"
  AutoExposureBracketing: string // ☆☆☆ "On"
  AutoISO: number // ☆☆☆ 100
  AutoLightingOptimizer: string // ☆☆☆ "Enable"
  AutoRotate: string // ☆☆☆ "None"
  AuxiliaryLens: string // ☆☆☆ "Off"
  AverageBlackLevel: string // ☆☆☆ "1024 1024 1024 1024"
  BWMode: string // ☆☆☆ "Off"
  BaseISO: number // ☆☆☆ 50
  Beep: string // ☆☆☆ "Off"
  BlackLevel: string // ☆☆☆ "600 600 600 600"
  BlackLevel2: string // ☆☆☆ "63 63 63 63"
  BlackMaskBottomBorder: number // ☆☆☆ 0
  BlackMaskLeftBorder: number // ☆☆☆ 0
  BlackMaskRightBorder: number // ☆☆☆ 0
  BlackMaskTopBorder: number // ☆☆☆ 0
  BlueBalance: number // ☆☆☆ 1.3125
  BodyFirmwareVersion: number // ☆☆☆ 73
  BracketMode: string // ☆☆☆ "Off"
  BracketShotNumber: number // ☆☆☆ 0
  BracketValue: number // ☆☆☆ 0
  Brightness: string // ☆☆☆ "Normal"
  BrightnessValue: number // ☆☆☆ 1.5703125
  BulbDuration: number // ☆☆☆ 0
  CameraID: string // ☆☆☆ "OLYMPUS DIGITAL CAMERA"
  CameraISO: string // ☆☆☆ "Auto"
  CameraOrientation: string // ☆☆☆ "Horizontal (normal)"
  CameraSettingsVersion: string // ☆☆☆ "0100"
  CameraTemperature: string // ☆☆☆ "27 C"
  CameraType: string // ★☆☆ "DV Camera"
  CameraType2: string // ☆☆☆ "u7040,S7040"
  CanonExposureMode: string // ☆☆☆ "Program AE"
  CanonFirmwareVersion: string // ☆☆☆ "Firmware Version 2.01"
  CanonFlashMode: string // ☆☆☆ "Auto"
  CanonImageHeight: number // ☆☆☆ 1840
  CanonImageSize: string // ☆☆☆ "Large"
  CanonImageType: string // ★☆☆ "IMG:iVIS DC50 JPEG"
  CanonImageWidth: number // ☆☆☆ 3264
  CanonModelID: string // ☆☆☆ "DC50"
  Categories: string // ☆☆☆ "(none)"
  CenterWeightedAreaSize: string // ☆☆☆ "12 mm"
  ChromaticAberrationCorr: string // ☆☆☆ "Off"
  ChromaticAberrationSetting: string // ☆☆☆ "On"
  ColorBalanceVersion: string // ☆☆☆ "0403"
  ColorControl: string // ☆☆☆ "24 1024 768 1024 16 256"
  ColorDataVersion: string // ☆☆☆ "5 (450D/1000D)"
  ColorHue: string // ☆☆☆ "Mode2"
  ColorMatrix: string // ☆☆☆ "366 -92 -18 -52 412 -104 -6 -108 370"
  ColorMode: string // ☆☆☆ "Color"
  ColorSpace: string // ☆☆☆ "sRGB"
  ColorTempAsShot: number // ☆☆☆ 4551
  ColorTempAuto: number // ☆☆☆ 4551
  ColorTempCloudy: number // ☆☆☆ 6000
  ColorTempDaylight: number // ☆☆☆ 5200
  ColorTempFlash: number // ☆☆☆ 6456
  ColorTempFluorescent: number // ☆☆☆ 3901
  ColorTempKelvin: number // ☆☆☆ 5190
  ColorTempMeasured: number // ☆☆☆ 4276
  ColorTempShade: number // ☆☆☆ 7000
  ColorTempTungsten: number // ☆☆☆ 3200
  ColorTemperature: number // ☆☆☆ 5200
  ColorTone: string // ☆☆☆ "Normal"
  ColorToneAuto: number // ☆☆☆ 0
  ColorToneFaithful: number // ☆☆☆ 0
  ColorToneLandscape: number // ☆☆☆ 0
  ColorToneNeutral: number // ☆☆☆ 0
  ColorTonePortrait: number // ☆☆☆ 0
  ColorToneStandard: number // ☆☆☆ 0
  ColorToneUserDef1: number // ☆☆☆ 0
  ColorToneUserDef2: number // ☆☆☆ 0
  ColorToneUserDef3: number // ☆☆☆ 0
  CommandDialsReverseRotation: string // ☆☆☆ "No"
  Compression: string // ☆☆☆ "JPEG (old-style)"
  CompressionFactor: number // ☆☆☆ 4
  ContinuousDrive: string // ☆☆☆ "Continuous"
  Contrast: string // ★☆☆ "Normal"
  ContrastAuto: number // ☆☆☆ 0
  ContrastDetectAF: string // ☆☆☆ "Off"
  ContrastDetectAFInFocus: string // ☆☆☆ "Yes"
  ContrastFaithful: number // ☆☆☆ 0
  ContrastLandscape: number // ☆☆☆ 0
  ContrastMonochrome: number // ☆☆☆ 0
  ContrastNeutral: number // ☆☆☆ 0
  ContrastPortrait: number // ☆☆☆ 0
  ContrastSetting: string // ☆☆☆ "0 (min -2, max 2)"
  ContrastStandard: number // ☆☆☆ 0
  ContrastUserDef1: number // ☆☆☆ 0
  ContrastUserDef2: number // ☆☆☆ 0
  ContrastUserDef3: number // ☆☆☆ 0
  ControlMode: string // ☆☆☆ "n/a"
  ConversionLens: string // ☆☆☆ ""
  CoringFilter: number // ☆☆☆ 2176
  CountryCode: string // ☆☆☆ ""
  CropBottomMargin: number // ☆☆☆ 0
  CropHeight: number // ☆☆☆ 3456
  CropHiSpeed: string // ☆☆☆ "Off (4620x3084 cropped to 4620x3084 at pixel 0,0)"
  CropLeft: string // ☆☆☆ "8 0"
  CropLeftMargin: number // ☆☆☆ 0
  CropRightMargin: number // ☆☆☆ 0
  CropTop: string // ☆☆☆ "8 0"
  CropTopMargin: number // ☆☆☆ 0
  CropWidth: number // ☆☆☆ 4608
  CroppedImageHeight: number // ☆☆☆ 3456
  CroppedImageLeft: number // ☆☆☆ 0
  CroppedImageTop: number // ☆☆☆ 0
  CroppedImageWidth: number // ☆☆☆ 5184
  CustomControls: string // ☆☆☆ "0 0 1 0 0 1"
  CustomPictureStyleFileName: string // ☆☆☆ ""
  CustomSaturation: string // ☆☆☆ "0 (min -2, max 2)"
  DataDump: string // ☆☆☆ "(Binary data 494 bytes, use -b option to extract)"
  DataDump2: string // ☆☆☆ "(Binary data 4048 bytes, use -b option to extract)"
  DateDisplayFormat: ExifDateTime // ☆☆☆ "D/M/Y"
  DateStampMode: string // ☆☆☆ "Off"
  DateTimeUTC: ExifDateTime // ☆☆☆ {"year":2015,"month":2,"day":6,"hour":6,"minute":20,"second":9}
  DaylightSavings: string // ☆☆☆ "Off"
  DeviceType: string // ☆☆☆ "Compact Digital Camera"
  DialDirectionTvAv: string // ☆☆☆ "Normal"
  DigitalGain: number // ☆☆☆ 0
  DigitalZoom: string // ★☆☆ "None"
  DirectoryIndex: number // ☆☆☆ 100
  DirectoryNumber: number // ☆☆☆ 100
  DisplayAperture: number // ☆☆☆ 3.9
  DistortionCorrection: string // ☆☆☆ "Off"
  DistortionCorrection2: string // ☆☆☆ "On"
  DriveMode: string // ☆☆☆ "Single Shot"
  DustRemovalData: string // ☆☆☆ "(Binary data 1024 bytes, use -b option to extract)"
  ETTLII: string // ☆☆☆ "Evaluative"
  EasyMode: string // ☆☆☆ "Manual"
  EffectiveMaxAperture: number // ☆☆☆ 2.9
  Enhancer: number // ☆☆☆ 42
  EquipmentVersion: string // ☆☆☆ "0100"
  ExitPupilPosition: string // ☆☆☆ "93.1 mm"
  ExposureBracketValue: number // ☆☆☆ 0
  ExposureCompensation: number // ☆☆☆ 0
  ExposureDelayMode: string // ☆☆☆ "Off"
  ExposureDifference: number // ☆☆☆ 0
  ExposureLevelIncrements: string // ☆☆☆ "1/3 Stop"
  ExposureMode: string // ☆☆☆ "Program"
  ExposureShift: string // ☆☆☆ "undef"
  ExposureTime: string // ☆☆☆ "1/64"
  ExposureTuning: number // ☆☆☆ 0
  ExtendedWBDetect: string // ☆☆☆ "Off"
  Extender: string // ☆☆☆ "None"
  ExtenderFirmwareVersion: number // ☆☆☆ 0
  ExtenderModel: string // ☆☆☆ ""
  ExtenderSerialNumber: string // ☆☆☆ ""
  ExternalFlash: string // ☆☆☆ "Off"
  ExternalFlashBounce: string // ☆☆☆ "Bounce or Off"
  ExternalFlashCompensation: number // ☆☆☆ 0
  ExternalFlashExposureComp: number // ☆☆☆ 0
  ExternalFlashFirmware: string // ☆☆☆ "n/a"
  ExternalFlashFlags: string // ☆☆☆ "(none)"
  ExternalFlashGValue: number // ☆☆☆ 0
  ExternalFlashMode: number // ☆☆☆ 0
  ExternalFlashZoom: number // ☆☆☆ 0
  FNumber: number // ☆☆☆ 2.9
  Face1Position: string // ☆☆☆ "12 -54"
  FaceDetect: string // ☆☆☆ "Off"
  FaceDetectArea: string // ☆☆☆ "(Binary data 383 bytes, use -b option to extract)"
  FaceDetectFrameCrop: string // ☆☆☆ "0 0 0 0 0 0 0 0 0 0 0 0"
  FaceDetectFrameSize: string // ☆☆☆ "320 240"
  FaceRecognition: string // ☆☆☆ "Off"
  FaceWidth: number // ☆☆☆ 35
  FacesDetected: number // ☆☆☆ 0
  FileIndex: number // ☆☆☆ 285
  FileInfoVersion: string // ☆☆☆ "0100"
  FileNumber: string // ★☆☆ "196-9624"
  FilterEffect: string // ☆☆☆ "None"
  FilterEffectAuto: string // ☆☆☆ "n/a"
  FilterEffectMonochrome: string // ☆☆☆ "None"
  FilterEffectUserDef1: string // ☆☆☆ "None"
  FilterEffectUserDef2: string // ☆☆☆ "None"
  FilterEffectUserDef3: string // ☆☆☆ "None"
  Firmware: string // ☆☆☆ "73"
  FirmwareRevision: string // ☆☆☆ "1.00 rev 3.00"
  FirmwareVersion: string // ☆☆☆ "1.0.3"
  FisheyeFilter: string // ☆☆☆ "Off"
  FlashActivity: number // ☆☆☆ 0
  FlashBits: string // ☆☆☆ "E-TTL, Built-in"
  FlashChargeLevel: number // ☆☆☆ 0
  FlashColorFilter: string // ☆☆☆ "None"
  FlashCommanderMode: string // ☆☆☆ "Off"
  FlashCompensation: number // ☆☆☆ 0
  FlashControlMode: string // ☆☆☆ "Off"
  FlashDevice: string // ☆☆☆ "Unknown (0 0)"
  FlashExposureBracketValue: number // ☆☆☆ 0
  FlashExposureComp: number // ★☆☆ 0
  FlashExposureComp3: number // ☆☆☆ 0
  FlashExposureComp4: string // ☆☆☆ "-2/3"
  FlashExposureLock: string // ☆☆☆ "Off"
  FlashFirmwareVersion: number // ☆☆☆ 0
  FlashGNDistance: number // ☆☆☆ 0
  FlashGroupACompensation: number // ☆☆☆ 0
  FlashGroupAControlMode: string // ☆☆☆ "Off"
  FlashGroupBCompensation: number // ☆☆☆ 0
  FlashGroupBControlMode: string // ☆☆☆ "Off"
  FlashGroupCCompensation: number // ☆☆☆ 0
  FlashGroupCControlMode: string // ☆☆☆ "Off"
  FlashGuideNumber: number // ☆☆☆ 8.46875
  FlashInfoVersion: string // ☆☆☆ "0200"
  FlashIntensity: string // ☆☆☆ "n/a"
  FlashMeteringMode: string // ☆☆☆ "Off"
  FlashMode: string // ☆☆☆ "Did Not Fire"
  FlashModel: string // ☆☆☆ "None"
  FlashOutput: number // ☆☆☆ 175
  FlashRemoteControl: string // ☆☆☆ "Off"
  FlashSerialNumber: string // ☆☆☆ ""
  FlashSetting: string // ☆☆☆ "Normal"
  FlashShutterSpeed: string // ☆☆☆ "1/60 s"
  FlashSource: string // ☆☆☆ "None"
  FlashSyncSpeed: string // ☆☆☆ "1/250 s"
  FlashSyncSpeedAv: string // ☆☆☆ "Auto"
  FlashType: string // ☆☆☆ ""
  FocalLength: string // ☆☆☆ "15.53 mm"
  FocalPlaneDiagonal: string // ☆☆☆ "7.665 mm"
  FocalPlaneXSize: string // ☆☆☆ "5.44 mm"
  FocalPlaneYSize: string // ☆☆☆ "4.06 mm"
  FocalType: string // ☆☆☆ "Zoom"
  FocalUnits: string // ☆☆☆ "100/mm"
  FocusContinuous: string // ☆☆☆ "Continuous"
  FocusDistance: string // ☆☆☆ "3.98 m"
  FocusDistanceLower: string // ☆☆☆ "0 m"
  FocusDistanceUpper: string // ☆☆☆ "65.53 m"
  FocusInfoVersion: string // ☆☆☆ "0100"
  FocusMode: string // ★☆☆ "Single"
  FocusPointWrap: string // ☆☆☆ "No Wrap"
  FocusPosition: string // ☆☆☆ "0x22"
  FocusProcess: string // ☆☆☆ "AF Not Used"
  FocusRange: string // ★☆☆ "Auto"
  FocusStepCount: number // ☆☆☆ 646
  FocusStepInfinity: number // ☆☆☆ 642
  FocusStepNear: number // ☆☆☆ 692
  FocusingScreen: string // ☆☆☆ "Ec-CIV"
  GainBase: number // ☆☆☆ 256
  Gradation: string // ☆☆☆ "n/a; User-Selected"
  GrainyBWFilter: string // ☆☆☆ "Off"
  HDR: string // ☆☆☆ "Off"
  HDREffect: string // ☆☆☆ "Natural"
  HDRInfoVersion: string // ☆☆☆ "0200"
  HDRLevel: string // ☆☆☆ "Auto"
  HDRLevel2: string // ☆☆☆ "Auto"
  HDRSmoothing: string // ☆☆☆ "Off"
  HighISONoiseReduction: string // ☆☆☆ "Off"
  HighlightTonePriority: string // ☆☆☆ "Disable"
  HueAdjustment: string // ☆☆☆ "None"
  ISO: number // ☆☆☆ 100
  ISO2: number // ☆☆☆ 159
  ISOExpansion: string // ☆☆☆ "On"
  ISOExpansion2: string // ☆☆☆ "Off"
  ISOSelection: string // ☆☆☆ "Auto"
  ISOSetting: number // ☆☆☆ 100
  ISOSpeedIncrements: string // ☆☆☆ "1/3 Stop"
  ISOValue: number // ☆☆☆ 100
  ImageAdjustment: string // ☆☆☆ "Auto"
  ImageBoundary: string // ☆☆☆ "0 0 4608 3072"
  ImageDataSize: number // ☆☆☆ 5500790
  ImageOptimization: string // ☆☆☆ "Normal"
  ImageProcessing: string // ☆☆☆ ""
  ImageProcessingVersion: string // ☆☆☆ "0112"
  ImageQuality2: string // ☆☆☆ "SQ (5)"
  ImageStabilization: string // ☆☆☆ "On"
  ImageUniqueID: string // ☆☆☆ "25c584939cdf2fe47ac7af920c3ef487"
  IntelligentContrast: string // ☆☆☆ "Off"
  InternalFlash: string // ☆☆☆ "TTL"
  InternalFlashTable: number // ☆☆☆ 75
  InternalSerialNumber: string // ☆☆☆ "K0027622"
  LCDDisplayAtPowerOn: string // ☆☆☆ "Display"
  Lens: string // ☆☆☆ "11-27.5mm f/3.5-5.6"
  LensAFStopButton: string // ☆☆☆ "AF Stop"
  LensDataVersion: string // ☆☆☆ "0403"
  LensDistortionParams: string // ☆☆☆ "-30641 21134 32382 25674 17516 32364"
  LensFStops: number // ☆☆☆ 7.67
  LensFirmwareVersion: number // ☆☆☆ 1.004
  LensIDNumber: number // ☆☆☆ 101
  LensModel: string // ☆☆☆ "EF-S18-55mm f/3.5-5.6 IS"
  LensProperties: string // ☆☆☆ "0xc140"
  LensSerialNumber: string // ☆☆☆ "00002042bc"
  LensType: string // ★☆☆ "n/a"
  LightCondition: number // ☆☆☆ 0
  LightSource: string // ☆☆☆ "Speedlight"
  LightValueCenter: number // ☆☆☆ 1.4453125
  LightValuePeriphery: number // ☆☆☆ 1.765625
  LinearityUpperMargin: number // ☆☆☆ 10000
  LiveViewShooting: string // ☆☆☆ "Off"
  Location: string // ☆☆☆ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000…
  LocationInfoVersion: string // ☆☆☆ "0100"
  LongExposureNoiseReduction: string // ☆☆☆ "Off"
  LongExposureNoiseReduction2: string // ☆☆☆ "Off"
  MCUVersion: number // ☆☆☆ 107
  Macro: string // ☆☆☆ "Off"
  MacroLED: string // ☆☆☆ "Off"
  MacroMode: string // ★☆☆ "Unknown (0)"
  MagicFilter: string // ☆☆☆ "Off; 1280; 0; 0"
  MakerNoteVersion: number // ☆☆☆ 2.11
  ManometerPressure: string // ☆☆☆ "0 kPa"
  ManometerReading: string // ☆☆☆ "0 m, 0 ft"
  ManualFlash: string // ☆☆☆ "Off"
  ManualFlashOutput: string // ☆☆☆ "n/a"
  ManualFlashStrength: string // ☆☆☆ "n/a"
  ManualFocusDistance: string // ☆☆☆ "undef"
  MaxAperture: number // ☆☆☆ 2.9
  MaxApertureAtMaxFocal: number // ☆☆☆ 5.7
  MaxApertureAtMinFocal: number // ☆☆☆ 4.5
  MaxFaces: string // ☆☆☆ "16 16 16"
  MaxFocalLength: string // ★☆☆ "61 mm"
  MeasuredEV: number // ☆☆☆ 5
  MeasuredEV2: number // ☆☆☆ 12.625
  MeasuredRGGB: string // ☆☆☆ "471 1024 1024 581"
  MemoryCardNumber: number // ☆☆☆ 0
  MeteringMode: string // ★☆☆ "Evaluative"
  MeteringTime: string // ☆☆☆ "6 s"
  MinAperture: number // ☆☆☆ 6.9
  MinFocalLength: string // ★☆☆ "6.1 mm"
  MiniatureFilter: string // ☆☆☆ "Off"
  MiniatureFilterOrientation: string // ☆☆☆ "Horizontal"
  MiniatureFilterParameter: number // ☆☆☆ 0
  MiniatureFilterPosition: number // ☆☆☆ 0
  MirrorLockup: string // ☆☆☆ "Disable"
  ModelingFlash: string // ☆☆☆ "Off"
  ModifiedSaturation: string // ☆☆☆ "Off"
  MultiExposure: string // ☆☆☆ "Off"
  MultiExposureAutoGain: string // ☆☆☆ "Off"
  MultiExposureControl: string // ☆☆☆ "Additive"
  MultiExposureMode: string // ☆☆☆ "Off"
  MultiExposureShots: number // ☆☆☆ 0
  MultiExposureVersion: string // ☆☆☆ "0100"
  MultiFunctionLock: string // ☆☆☆ "On (quick control dial)"
  MultipleExposureMode: string // ☆☆☆ "Off; 1"
  MyColorMode: string // ☆☆☆ "Off"
  NDFilter: string // ☆☆☆ "n/a"
  NEFBitDepth: string // ☆☆☆ "n/a (JPEG)"
  NikonCaptureVersion: string // ☆☆☆ "OTHER"
  NoMemoryCard: string // ☆☆☆ "Release Locked"
  NoiseFilter: string // ☆☆☆ "n/a"
  NoiseReduction: string // ☆☆☆ "Off"
  NoiseReduction2: string // ☆☆☆ "(none)"
  NormalWhiteLevel: number // ☆☆☆ 14582
  NumAFPoints: number // ☆☆☆ 9
  OlympusImageHeight: number // ☆☆☆ 1536
  OlympusImageWidth: number // ☆☆☆ 2048
  OneTouchWB: string // ☆☆☆ "Off"
  OpticalZoomCode: string // ☆☆☆ "n/a"
  OriginalDecisionDataOffset: number // ☆☆☆ 0
  OriginalImageHeight: number // ☆☆☆ 3168
  OriginalImageWidth: number // ☆☆☆ 4752
  OwnerName: string // ☆☆☆ ""
  POILevel: number // ☆☆☆ 0
  PaintingFilter: string // ☆☆☆ "Off"
  PanoramaMode: string // ☆☆☆ "Off"
  PerChannelBlackLevel: string // ☆☆☆ "1023 1024 1023 1024"
  PeripheralIlluminationCorr: string // ☆☆☆ "On"
  PeripheralLighting: string // ☆☆☆ "Off"
  PeripheralLightingSetting: string // ☆☆☆ "Off"
  PeripheralLightingValue: number // ☆☆☆ 0
  PhaseDetectAF: string // ☆☆☆ "On (73-point)"
  PhotoEffect: string // ☆☆☆ "Off"
  PictureControlAdjust: string // ☆☆☆ "Default Settings"
  PictureControlBase: string // ☆☆☆ "Standard"
  PictureControlName: string // ☆☆☆ "Standard"
  PictureControlQuickAdjust: string // ☆☆☆ "Normal"
  PictureControlVersion: string // ☆☆☆ "0100"
  PictureMode: string // ☆☆☆ "i-Enhance; 2"
  PictureModeBWFilter: string // ☆☆☆ "n/a"
  PictureModeContrast: string // ☆☆☆ "0 (min -2, max 2)"
  PictureModeEffect: string // ☆☆☆ "Standard"
  PictureModeSaturation: string // ☆☆☆ "0 (min -2, max 2)"
  PictureModeSharpness: string // ☆☆☆ "0 (min -2, max 2)"
  PictureModeTone: string // ☆☆☆ "n/a"
  PictureStyle: string // ☆☆☆ "None"
  PictureStylePC: string // ☆☆☆ "None; None; None"
  PictureStyleUserDef: string // ☆☆☆ "Standard; Standard; Standard"
  PictureWizardColor: number // ☆☆☆ 0
  PictureWizardContrast: number // ☆☆☆ -4
  PictureWizardMode: string // ☆☆☆ "Standard"
  PictureWizardSaturation: number // ☆☆☆ -4
  PictureWizardSharpness: string // ☆☆☆ "-4"
  PowerUpTime: string // ☆☆☆ "0000:00:00 00:00:00"
  PreCaptureFrames: number // ☆☆☆ 0
  PreviewImageLength: number // ☆☆☆ 347190
  PreviewImageStart: number // ☆☆☆ 1296968
  PreviewImageValid: string // ☆☆☆ "Yes"
  PrimaryAFPoint: number // ☆☆☆ 4
  ProgramShift: number // ☆☆☆ 0
  Quality: string // ★☆☆ "Superfine"
  RawDataByteOrder: string // ☆☆☆ "Little-endian (Intel, II)"
  RawDataCFAPattern: string // ☆☆☆ "Swap"
  RawDevColorSpace: string // ☆☆☆ "sRGB"
  RawDevContrastValue: string // ☆☆☆ "0 0 0"
  RawDevEditStatus: string // ☆☆☆ "Original"
  RawDevEngine: string // ☆☆☆ "High Speed"
  RawDevExposureBiasValue: number // ☆☆☆ 0
  RawDevGrayPoint: string // ☆☆☆ "0 0 0"
  RawDevMemoryColorEmphasis: number // ☆☆☆ 0
  RawDevNoiseReduction: string // ☆☆☆ "(none)"
  RawDevSaturationEmphasis: string // ☆☆☆ "0 0 0"
  RawDevSettings: string // ☆☆☆ "(none)"
  RawDevSharpnessValue: string // ☆☆☆ "0 0 0"
  RawDevVersion: string // ☆☆☆ "0100"
  RawDevWBFineAdjustment: number // ☆☆☆ 0
  RawDevWhiteBalanceValue: number // ☆☆☆ 0
  RawJpgSize: string // ☆☆☆ "Large"
  RawMeasuredRGGB: string // ☆☆☆ "40661 82449 82146 41069"
  RecordMode: string // ☆☆☆ "JPEG"
  RedBalance: number // ☆☆☆ 1.4921875
  Resolution: number // ☆☆☆ 2
  ResolutionUnit: string // ☆☆☆ "inches"
  RetouchHistory: string // ☆☆☆ "None"
  RetouchInfoVersion: string // ☆☆☆ "0200"
  RetouchNEFProcessing: string // ☆☆☆ "Off"
  RetractLensOnPowerOff: string // ☆☆☆ "Enable"
  ReverseIndicators: string // ☆☆☆ "+ 0 -"
  Rotation: number // ☆☆☆ 0
  RunTimeEpoch: number // ☆☆☆ 0
  RunTimeFlags: string // ☆☆☆ "Valid"
  RunTimeScale: number // ☆☆☆ 1000000000
  RunTimeValue: number // ☆☆☆ 98536337937083
  SRAWQuality: string // ☆☆☆ "n/a"
  SafetyShift: string // ☆☆☆ "Disable"
  SamsungModelID: string // ☆☆☆ "Various Models (0x3000000)"
  Saturation: string // ★☆☆ "Normal"
  SaturationAuto: number // ☆☆☆ 0
  SaturationFaithful: number // ☆☆☆ 0
  SaturationLandscape: number // ☆☆☆ 0
  SaturationNeutral: number // ☆☆☆ 0
  SaturationPortrait: number // ☆☆☆ 0
  SaturationStandard: number // ☆☆☆ 0
  SaturationUserDef1: number // ☆☆☆ 0
  SaturationUserDef2: number // ☆☆☆ 0
  SaturationUserDef3: number // ☆☆☆ 0
  SceneAssist: string // ☆☆☆ ""
  SceneDetect: number // ☆☆☆ 2
  SceneMode: string // ☆☆☆ ""
  SelfTimer: string // ☆☆☆ "Off"
  SelfTimer2: number // ☆☆☆ 0.1
  SelfTimerTime: string // ☆☆☆ "10 s"
  SensorBlueLevel: number // ☆☆☆ 0
  SensorBottomBorder: number // ☆☆☆ 2322
  SensorCalibration: string // ☆☆☆ "0 0"
  SensorHeight: number // ☆☆☆ 2328
  SensorLeftBorder: number // ☆☆☆ 52
  SensorPixelSize: string // ☆☆☆ "7.8 x 7.8 um"
  SensorRedLevel: number // ☆☆☆ 0
  SensorRightBorder: number // ☆☆☆ 3507
  SensorTemperature: string // ☆☆☆ "24 24 0 C"
  SensorTopBorder: number // ☆☆☆ 19
  SensorWidth: number // ☆☆☆ 3516
  SequenceNumber: number // ☆☆☆ 0
  SerialNumber: string // ☆☆☆ "0320131248"
  SerialNumberFormat: string // ☆☆☆ "Format 2"
  SetButtonWhenShooting: string // ☆☆☆ "Default (no function)"
  ShadingCompensation: string // ☆☆☆ "Off"
  ShadingCompensation2: string // ☆☆☆ "On"
  Sharpness: string // ★☆☆ "0"
  SharpnessAuto: number // ☆☆☆ 3
  SharpnessFactor: number // ☆☆☆ 592
  SharpnessFaithful: number // ☆☆☆ 0
  SharpnessFrequency: string // ☆☆☆ "n/a"
  SharpnessLandscape: number // ☆☆☆ 4
  SharpnessMonochrome: number // ☆☆☆ 3
  SharpnessNeutral: number // ☆☆☆ 0
  SharpnessPortrait: number // ☆☆☆ 2
  SharpnessSetting: string // ☆☆☆ "0 (min -2, max 2)"
  SharpnessStandard: number // ☆☆☆ 3
  SharpnessUserDef1: number // ☆☆☆ 3
  SharpnessUserDef2: number // ☆☆☆ 3
  SharpnessUserDef3: number // ☆☆☆ 3
  ShootingMode: string // ☆☆☆ "Delay"
  ShotInfoVersion: string // ☆☆☆ "0400"
  ShutterButtonAFOnButton: string // ☆☆☆ "Metering + AF start"
  ShutterCount: number // ☆☆☆ 266
  ShutterCurtainSync: string // ☆☆☆ "1st-curtain sync"
  ShutterSpeedValue: string // ☆☆☆ "1/128"
  SlowShutter: string // ☆☆☆ "n/a"
  SoftFocusFilter: string // ☆☆☆ "Off"
  SpecialMode: string // ☆☆☆ "Normal, Sequence: 0, Panorama: (none)"
  SpecularWhiteLevel: number // ☆☆☆ 15120
  SpotMeteringMode: string // ☆☆☆ "Center"
  SuperMacro: string // ☆☆☆ "Off"
  SuperimposedDisplay: string // ☆☆☆ "On"
  TargetAperture: number // ☆☆☆ 2.8
  TargetExposureTime: string // ☆☆☆ "1/60"
  TextEncoding: string // ☆☆☆ "n/a"
  ThumbnailImageValidArea: string // ☆☆☆ "0 0 0 0"
  TimeZone: string // ☆☆☆ "+00:00"
  TimeZoneCity: string // ☆☆☆ "London"
  ToneComp: string // ☆☆☆ "Auto"
  ToneCurve: string // ☆☆☆ "Standard"
  ToneLevel: string // ☆☆☆ "Highlights; 0; -7; 7; Shadows; 0; -7; 7; Midtones; 0; -7; 7; 0; 0; 0; 0; 0; 0;…
  ToningEffect: string // ☆☆☆ "None"
  ToningEffectAuto: string // ☆☆☆ "n/a"
  ToningEffectMonochrome: string // ☆☆☆ "None"
  ToningEffectUserDef1: string // ☆☆☆ "None"
  ToningEffectUserDef2: string // ☆☆☆ "None"
  ToningEffectUserDef3: string // ☆☆☆ "None"
  ToningSaturation: string // ☆☆☆ "n/a"
  ToyCameraFilter: string // ☆☆☆ "Off"
  USMLensElectronicMF: string // ☆☆☆ "Enable After AF"
  UserDef1PictureStyle: string // ☆☆☆ "Standard"
  UserDef2PictureStyle: string // ☆☆☆ "Standard"
  UserDef3PictureStyle: string // ☆☆☆ "Standard"
  VFDisplayIllumination: string // ☆☆☆ "Auto"
  VRDOffset: number // ☆☆☆ 0
  VRInfoVersion: string // ☆☆☆ "0101"
  VRMode: string // ☆☆☆ "Normal"
  ValidAFPoints: number // ☆☆☆ 9
  ValidBits: string // ☆☆☆ "10 0"
  VariProgram: string // ☆☆☆ ""
  VibrationReduction: string // ☆☆☆ "Off"
  VignetteControl: string // ☆☆☆ "Off"
  VignettingCorrVersion: number // ☆☆☆ 0
  WBBracketMode: string // ☆☆☆ "Off"
  WBBracketValueAB: number // ☆☆☆ 0
  WBBracketValueGM: number // ☆☆☆ 0
  WBMode: string // ☆☆☆ "Auto"
  WBShiftAB: number // ☆☆☆ 0
  WBShiftGM: number // ☆☆☆ 0
  WB_GLevel: number // ☆☆☆ 0
  WB_GRBGLevels: string // ☆☆☆ "256 454 370 256"
  WB_RBGGLevels: string // ☆☆☆ "0 0 0 0"
  WB_RBLevels: string // ☆☆☆ "1.59375 2.1640625 1 1"
  WB_RGGBLevelsAsShot: string // ☆☆☆ "2338 1019 1019 1587"
  WB_RGGBLevelsAuto: string // ☆☆☆ "2338 1023 1023 1587"
  WB_RGGBLevelsCloudy: string // ☆☆☆ "2639 1023 1023 1353"
  WB_RGGBLevelsCustom: string // ☆☆☆ "128 128 128 128"
  WB_RGGBLevelsDaylight: string // ☆☆☆ "2425 1023 1023 1492"
  WB_RGGBLevelsFlash: string // ☆☆☆ "2735 1023 1023 1306"
  WB_RGGBLevelsFluorescent: string // ☆☆☆ "2038 1023 1023 1969"
  WB_RGGBLevelsKelvin: string // ☆☆☆ "2185 1024 1024 1535"
  WB_RGGBLevelsMeasured: string // ☆☆☆ "1912 1028 1019 1791"
  WB_RGGBLevelsShade: string // ☆☆☆ "2847 1023 1023 1249"
  WB_RGGBLevelsTungsten: string // ☆☆☆ "1597 1023 1023 2302"
  WatercolorFilter: string // ☆☆☆ "Off"
  WhiteBalance: string // ★☆☆ "Auto"
  WhiteBalance2: string // ☆☆☆ "Auto"
  WhiteBalanceBias: number // ☆☆☆ 0
  WhiteBalanceBlue: number // ☆☆☆ 0
  WhiteBalanceBracket: number // ☆☆☆ 0
  WhiteBalanceFineTune: string // ☆☆☆ "0 0"
  WhiteBalanceRed: number // ☆☆☆ 0
  WhiteBalanceTemperature: number // ☆☆☆ 5300
  WhiteBoard: number // ☆☆☆ 0
  XResolution: number // ☆☆☆ 300
  YCbCrPositioning: string // ☆☆☆ "Co-sited"
  YResolution: number // ☆☆☆ 300
  ZoomSourceWidth: number // ☆☆☆ 2584
  ZoomStepCount: number // ☆☆☆ 1
  ZoomTargetWidth: number // ☆☆☆ 2584
}

export interface JFIFTags {
  JFIFVersion: number // ☆☆☆ 1.01
  ResolutionUnit: string // ☆☆☆ "inches"
  XResolution: number // ☆☆☆ 72
  YResolution: number // ☆☆☆ 72
}

export interface XMPTags {
  About: string // ☆☆☆ "uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b"
  ApertureValue: number // ☆☆☆ 6.3
  BitsPerSample: number[] // ☆☆☆ [8,8,8]
  ColorMode: string // ☆☆☆ "RGB"
  ColorSpace: string // ☆☆☆ "sRGB"
  CreateDate: ExifDateTime // ☆☆☆ {"year":2015,"month":11,"day":11,"hour":11,"minute":27,"second":49}
  CreatorTool: string // ☆☆☆ "Photos 1.0.1"
  CustomRendered: string // ☆☆☆ "Normal"
  DateCreated: ExifDateTime // ☆☆☆ {"year":2015,"month":11,"day":11,"hour":11,"minute":27,"second":49}
  DateTimeDigitized: ExifDateTime // ☆☆☆ {"year":2010,"month":12,"day":19,"hour":15,"minute":23,"second":21}
  DateTimeOriginal: ExifDateTime // ☆☆☆ {"year":2010,"month":12,"day":19,"hour":15,"minute":23,"second":21}
  ExifImageHeight: number // ☆☆☆ 3456
  ExifImageWidth: number // ☆☆☆ 5184
  ExifVersion: string // ☆☆☆ "0230"
  ExposureCompensation: number // ☆☆☆ 0
  ExposureMode: string // ☆☆☆ "Auto"
  ExposureTime: string // ☆☆☆ "1/400"
  FNumber: number // ☆☆☆ 6.3
  Firmware: string // ☆☆☆ "3.6.1"
  FlashCompensation: number // ☆☆☆ 0
  FlashFired: boolean // ☆☆☆ false
  FlashFunction: boolean // ☆☆☆ false
  FlashMode: string // ☆☆☆ "Off"
  FlashRedEyeMode: boolean // ☆☆☆ false
  FlashReturn: string // ☆☆☆ "No return detection"
  FocalLength: string // ☆☆☆ "250.0 mm"
  ICCProfileName: string // ☆☆☆ "sRGB IEC61966-2.1"
  ISO: number // ☆☆☆ 1600
  ImageHeight: number // ☆☆☆ 3456
  ImageWidth: number // ☆☆☆ 5184
  Label: string // ☆☆☆ "選択"
  Lens: string // ☆☆☆ "iPhone 6 Plus back camera 4.15mm f/2.2"
  LensInfo: string // ☆☆☆ "4.15mm f/2.2"
  Make: string // ☆☆☆ "Canon"
  MaxApertureValue: number // ☆☆☆ 5.7
  MetadataDate: ExifDateTime // ☆☆☆ {"year":2014,"month":11,"day":11,"hour":15,"minute":27,"second":29,"tzoffsetMin…
  MeteringMode: string // ☆☆☆ "Multi-segment"
  Model: string // ☆☆☆ "Canon EOS Kiss X5"
  ModifyDate: ExifDateTime // ☆☆☆ {"year":2015,"month":11,"day":11,"hour":11,"minute":27,"second":49}
  Orientation: string // ☆☆☆ "Horizontal (normal)"
  Rating: number // ☆☆☆ 2
  RatingPercent: number // ☆☆☆ 0
  ResolutionUnit: string // ☆☆☆ "inches"
  SceneCaptureType: string // ☆☆☆ "Standard"
  ShutterSpeedValue: string // ☆☆☆ "1/400"
  Urgency: string // ☆☆☆ "1 (most urgent)"
  WhiteBalance: string // ☆☆☆ "Auto"
  XMPToolkit: string // ☆☆☆ "XMP Core 5.4.0"
  XResolution: number // ☆☆☆ 72
  YResolution: number // ☆☆☆ 72
}

export interface PhotoshopTags {
  IPTCDigest: string // ☆☆☆ "d41d8cd98f00b204e9800998ecf8427e"
}

export interface ICC_ProfileTags {
  BlueMatrixColumn: string // ☆☆☆ "0.14307 0.06061 0.7141"
  BlueTRC: string // ☆☆☆ "(Binary data 2060 bytes, use -b option to extract)"
  CMMFlags: string // ☆☆☆ "Not Embedded, Independent"
  ColorSpaceData: string // ☆☆☆ "RGB "
  ConnectionSpaceIlluminant: string // ☆☆☆ "0.9642 1 0.82491"
  DeviceAttributes: string // ☆☆☆ "Reflective, Glossy, Positive, Color"
  DeviceManufacturer: string // ☆☆☆ "IEC "
  DeviceMfgDesc: string // ☆☆☆ "IEC http://www.iec.ch"
  DeviceModel: string // ☆☆☆ "sRGB"
  DeviceModelDesc: string // ☆☆☆ "IEC 61966-2.1 Default RGB colour space - sRGB"
  GreenMatrixColumn: string // ☆☆☆ "0.38515 0.71687 0.09708"
  GreenTRC: string // ☆☆☆ "(Binary data 2060 bytes, use -b option to extract)"
  MediaBlackPoint: string // ☆☆☆ "0 0 0"
  MediaWhitePoint: string // ☆☆☆ "0.95045 1 1.08905"
  PrimaryPlatform: string // ☆☆☆ "Microsoft Corporation"
  ProfileCMMType: string // ☆☆☆ "Lino"
  ProfileClass: string // ☆☆☆ "Display Device Profile"
  ProfileConnectionSpace: string // ☆☆☆ "XYZ "
  ProfileCopyright: string // ☆☆☆ "Copyright (c) 1998 Hewlett-Packard Company"
  ProfileCreator: string // ☆☆☆ "HP  "
  ProfileDateTime: ExifDateTime // ☆☆☆ {"year":1998,"month":2,"day":9,"hour":6,"minute":49,"second":0}
  ProfileDescription: string // ☆☆☆ "sRGB IEC61966-2.1"
  ProfileFileSignature: string // ☆☆☆ "acsp"
  ProfileID: number // ☆☆☆ 0
  ProfileVersion: string // ☆☆☆ "2.1.0"
  RedMatrixColumn: string // ☆☆☆ "0.43607 0.22249 0.01392"
  RedTRC: string // ☆☆☆ "(Binary data 2060 bytes, use -b option to extract)"
  RenderingIntent: string // ☆☆☆ "Perceptual"
  Technology: string // ☆☆☆ "Cathode Ray Tube Display"
}

export interface IPTCTags {
  ApplicationRecordVersion: number // ☆☆☆ 4
  DateCreated: ExifDateTime // ☆☆☆ undefined
  TimeCreated: string // ☆☆☆ "13:15:35"
}

export interface MPFTags {
  DependentImage1EntryNumber: number // ☆☆☆ 0
  DependentImage2EntryNumber: number // ☆☆☆ 0
  ImageUIDList: string // ☆☆☆ "(Binary data 66 bytes, use -b option to extract)"
  MPFVersion: string // ☆☆☆ "0100"
  MPImageFlags: string // ☆☆☆ "Dependent child image"
  MPImageFormat: string // ☆☆☆ "JPEG"
  MPImageLength: number // ☆☆☆ 681513
  MPImageStart: number // ☆☆☆ 7732736
  MPImageType: string // ☆☆☆ "Large Thumbnail (full HD equivalent)"
  NumberOfImages: number // ☆☆☆ 2
  TotalFrames: number // ☆☆☆ 1
}

export interface PrintIMTags {
  PrintIMVersion: string // ☆☆☆ "0300"
}

export interface APP4Tags {
  PreviewImageHeight: number // ☆☆☆ 776
  PreviewImageWidth: number // ☆☆☆ 1296
  PreviewQuality: number // ☆☆☆ 85
}

export interface Tags extends
  ExifToolTags,
  FileTags,
  EXIFTags,
  CompositeTags,
  MakerNotesTags,
  JFIFTags,
  XMPTags,
  PhotoshopTags,
  ICC_ProfileTags,
  IPTCTags,
  MPFTags,
  PrintIMTags,
  APP4Tags {
  SourceFile: string
  warnings: string[]
}

export interface GroupedTags {
  SourceFile: string
  warnings: string[]
  ExifTool: ExifToolTags
  File: FileTags
  EXIF: EXIFTags
  Composite: CompositeTags
  MakerNotes: MakerNotesTags
  JFIF: JFIFTags
  XMP: XMPTags
  Photoshop: PhotoshopTags
  ICC_Profile: ICC_ProfileTags
  IPTC: IPTCTags
  MPF: MPFTags
  PrintIM: PrintIMTags
  APP4: APP4Tags
}
